### ISSUE TITLE
0.1.0 crash on Samsung Galaxy S5

### ISSUE THREAD

**Issue by brendanhoar** [Yubico/yubioath-android#10]
The newly released 0.1.0 seems to be crashing on my Samsung Galaxy S5 whenever it (successfully?) reads the Neo. I've sent in the crash report via the automated system. Luckily I also kept the credential I needed in slot 2 for YubiTOTP use. 

Here's a manual excerpt:

Exception class name
java.lang.ClassCastException

Source file
SharePreferencesImpl.java

Source Class
android.app.SharePreferencesImpl

Source method
getStringSet

Line number
232

beginning of stack trace (perhaps some typos in my transcription)
java.lang.ClassCastException: java.lang.String cannot be cast to java.util.Set at android.app.SharedPreferencesImpl.getStringSet(SharedPreferencesImpl.java:232) at com.yubico.yubioath.c.a.a(Unknown Source) at com.yubico.yubioath.c.b.a(Unknown Source) at com.yubico.yubioath.c.b.<init>(Unknown Source) at com.yubico.yubioath.MainActivity.onNewIntenet...

Brendan

**Comment by dainnilsson** [comment]
I assume you're referring to 0.1.10 (not 0.1.0). This has already been fixed and a new version (0.1.11) has been released, and should be available in the Google play store, or from https://developers.yubico.com/yubioath-android/Releases/.

**Comment by brendanhoar** [comment]
I'll check it out. I saw an update yesterday to 0.1.10, and figured it was
the newest and was testing against that.

Checking now, there's another update 0.1.11.

Maybe I was just behind in updates and your recent one hadn't quite made it
to the public side of the store?

Testing...

Yup, that worked. No crash. Thanks a bunch!

Brendan

**Comment by dainnilsson** [comment]
Great!

**Comment by brendanhoar** [comment]
Now I'll just report a bug in the NEWS file:
"* Version 0.1.11 released 2015-02-16" should be
"* Version 0.1.11 released 2015-02-06"

:P

But seriously, thanks again for the quick turnaround.

Brendan

**Comment by dainnilsson** [comment]
Thanks, I'll fix that!
