### ISSUE TITLE
iOS Support - iOS 13

### ISSUE THREAD

**Issue by sarthurdev** [Yubico/yubioath-android#100]
Seems like the time is finally here, NFC writing support coming in iOS 13.

Any plans to support iOS?

Source: https://gototags.com/blog/apple-expands-nfc-on-iphone-in-ios-13/

**Comment by rggjan** [comment]
That would be awesome! See also #91

**Comment by sarthurdev** [comment]
https://www.yubico.com/2019/09/yubico-ios-authentication-expands-to-include-nfc/

Been announced that an iOS app will be released in the coming months.
