### ISSUE TITLE
Issues reading Yubikey 5 OTP

### ISSUE THREAD

**Issue by Archcry** [Yubico/yubioath-android#101]
Hello,

I recently installed LineageOS 16 on my oneplus 3. I am trying to read my one time passwords with the Yubico Authenticator app but unfortunately I only manage to get a "Error in yubikey communication error!". I am not really sure what causes the issue but found a clue in the logcat I made.

```
06-28 08:32:30.897  4518  4546 E yubioath: Error using OathClient
06-28 08:32:30.897  4518  4546 E yubioath: java.io.IOException: Transceive length exceeds supported maximum
06-28 08:32:30.897  4518  4546 E yubioath: 	at android.nfc.TransceiveResult.getResponseOrThrow(TransceiveResult.java:50)
06-28 08:32:30.897  4518  4546 E yubioath: 	at android.nfc.tech.BasicTagTechnology.transceive(BasicTagTechnology.java:151)
06-28 08:32:30.897  4518  4546 E yubioath: 	at android.nfc.tech.IsoDep.transceive(IsoDep.java:172)
06-28 08:32:30.897  4518  4546 E yubioath: 	at nordpol.android.AndroidCard.transceive(:1)
06-28 08:32:30.897  4518  4546 E yubioath: 	at c.c.a.f.c.a(:1)
06-28 08:32:30.897  4518  4546 E yubioath: 	at c.c.a.d.e.a(:22)
06-28 08:32:30.897  4518  4546 E yubioath: 	at c.c.a.d.e.a(:18)
06-28 08:32:30.897  4518  4546 E yubioath: 	at c.c.a.d.e.<init>(:3)
06-28 08:32:30.897  4518  4546 E yubioath: 	at c.c.a.a.d.<init>(:2)
06-28 08:32:30.897  4518  4546 E yubioath: 	at c.c.a.g.e.a(:18)
06-28 08:32:30.897  4518  4546 E yubioath: 	at c.c.a.g.f.a(:8)
06-28 08:32:30.897  4518  4546 E yubioath: 	at d.c.a.b.a.a.c(:2)
06-28 08:32:30.897  4518  4546 E yubioath: 	at e.a.a.X$a.a(:11)
06-28 08:32:30.897  4518  4546 E yubioath: 	at e.a.a.V.run(:1)
06-28 08:32:30.897  4518  4546 E yubioath: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
06-28 08:32:30.897  4518  4546 E yubioath: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
06-28 08:32:30.897  4518  4546 E yubioath: 	at java.lang.Thread.run(Thread.java:764)
```

The full logcat is available [here](https://pastebin.com/25x3UkXx).

I am trying to figure out if the issue is caused by the Yubico app or by LineageOS but unfortunately I am not to familiar with android logcat files so I would be more than happy if you guys could point me in the right direction here.

**Comment by dainnilsson** [comment]
Might be related to #95, you might want to check that for clues. Although it looks like you're getting a different error message. What version of the app are you using?

**Comment by Archcry** [comment]
I am using version v2.1.0 of the Yubico Authenticator app. I also posted my issue on the [XDA forums](https://forum.xda-developers.com/showpost.php?p=79810033&postcount=2650) and nvertigo67 on XDA told me to try adding `ISO_DEP_MAX_TRANSCEIVE=0xFEFF` in my `libnfc-nxp.conf`. I'll try looking into that aswell.

**Comment by dainnilsson** [comment]
One other thing you can try is installing the latest 2.2.0 beta, you can get it from the Play Store by opting in to the beta channel for the app.

**Comment by Archcry** [comment]
The fix provided by nvertigo67 worked, I am going to try and get this fix inside the installer image for LineageOS :D
