### ISSUE TITLE
android-maven-plugin:4.1.0:proguard Unsupported class version number [52.0] (maximum 51.0, Java 1.7)

### ISSUE THREAD

**Issue by AxelNennker** [Yubico/yubioath-android#11]
Does not build with java8. 

Seems that a newer ProGuard is needed.
I downloaded it from here: http://sourceforge.net/projects/proguard/files/proguard/
and placed it in $ANDROID_HOME/tools.

Not sure what the best way to fix this is:
- require java7 or
- tell Google to update Android's proguard
- some maven trickery to download a new ProGuard if needed and use it

-Axel

[INFO] Changes detected - recompiling the module!
[INFO] Compiling 18 source files to /home/ignisvulpis/development/yubioath-android/target/classes
[INFO] 
[INFO] --- android-maven-plugin:4.1.0:emma (default-emma) @ yubioath ---
[INFO] 
[INFO] --- android-maven-plugin:4.1.0:proguard (default-proguard) @ yubioath ---
[INFO] Proguarding output
[INFO] java.io.IOException: Can't read [/usr/lib/jvm/java-8-oracle/jre/lib/rt.jar](Can't process class [com/oracle/net/Sdp$1.class] %28Unsupported class version number [52.0] %28maximum 51.0, Java 1.7%29%29)
[INFO]  at proguard.InputReader.readInput(InputReader.java:230)
[INFO]  at proguard.InputReader.readInput(InputReader.java:200)
[INFO]  at proguard.InputReader.readInput(InputReader.java:178)
[INFO]  at proguard.InputReader.execute(InputReader.java:100)
[INFO]  at proguard.ProGuard.readInput(ProGuard.java:196)
[INFO]  at proguard.ProGuard.execute(ProGuard.java:78)
[INFO]  at proguard.ProGuard.main(ProGuard.java:492)
[INFO] Caused by: java.io.IOException: Can't process class [com/oracle/net/Sdp$1.class](Unsupported class version number [52.0] %28maximum 51.0, Java 1.7%29)
[INFO]  at proguard.io.ClassReader.read(ClassReader.java:112)
[INFO]  at proguard.io.FilteredDataEntryReader.read(FilteredDataEntryReader.java:87)
[INFO]  at proguard.io.JarReader.read(JarReader.java:65)
[INFO]  at proguard.io.DirectoryPump.readFiles(DirectoryPump.java:65)
[INFO]  at proguard.io.DirectoryPump.pumpDataEntries(DirectoryPump.java:53)
[INFO]  at proguard.InputReader.readInput(InputReader.java:226)
[INFO]  ... 6 more
[INFO] Caused by: java.lang.UnsupportedOperationException: Unsupported class version number [52.0](maximum 51.0, Java 1.7)
[INFO]  at proguard.classfile.util.ClassUtil.checkVersionNumbers(ClassUtil.java:140)
[INFO]  at proguard.classfile.io.LibraryClassReader.visitLibraryClass(LibraryClassReader.java:89)
[INFO]  at proguard.classfile.LibraryClass.accept(LibraryClass.java:301)
[INFO]  at proguard.io.ClassReader.read(ClassReader.java:86)
[INFO]  ... 11 more
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2:26.925s
[INFO] Finished at: Fri Apr 24 17:41:20 CEST 2015
[INFO] Final Memory: 24M/159M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.simpligility.maven.plugins:android-maven-plugin:4.1.0:proguard (default-proguard) on project yubioath: MojoExecutionException: ANDROID-040-001: Could not execute: Command = /bin/sh -c cd /home/ignisvulpis/development/yubioath-android && /usr/lib/jvm/java-8-oracle/jre/bin/java -Xmx512M -jar /home/ignisvulpis/Android/Sdk/tools/proguard/lib/proguard.jar @"/home/ignisvulpis/development/yubioath-android/target/proguard/temp_config.cfg", Result = 1 -> [Help 1]

**Comment by dainnilsson** [comment]
Thanks. I don't consider this high priority at the moment, but I'll take a look the next time I work on the project. If it turns out to be too much of a hassle we might just have to require Java 7 for building.

**Comment by Tomorrowhi** [comment]
Thanks

**Comment by dainnilsson** [comment]
Closing this as I don't think it's a problem anymore.
