### ISSUE TITLE
How to backup the app to save credentials in case a factory reset is required?

### ISSUE THREAD

**Issue by chakathebirdz** [Yubico/yubioath-android#110]
I don't know how to make a backup of the app with it's data. This leaves me completely vulnerable if I need to perform a factory reset or if my phone is lost. Ideally, the app would be cloud/internet base and synced online automatically similar to how lastpass works. But it spreads the app was not designed this way.

Looking forward to your feedback as I have become completely depended on this app for accessing many of my services.

**Comment by dainnilsson** [comment]
All credentials are stored on your YubiKey, and will still be there if you factory reset or replace your phone.
Data which is stored in the app itself include the app settings, custom icons, and "remembered" passwords. While there is no built-in way of exporting this data, there are third party applications which should allow you to backup the app along with the settings, but we have not tested these, nor do we support them.
