### ISSUE TITLE
Wipe Clipboard

### ISSUE THREAD

**Issue by mcclaneonfire** [Yubico/yubioath-android#116]
In the old Yubiclip app it is possible to set "wipe clipboard". Would be more secure to implement that in the Authenticator aswell, right?

**Comment by imakhalova** [comment]
Thank you so much for your request.
YubiClip obtains One-Time-Passwords that doesn't depend on time, and they valid til your YubiCloud server invalidates it.
While OTPs in Authenticator usually valid for 30 seconds only (TOTP). There is no much sense to secure this code after that.
But if you really cautious you can also wipe your clipboard by coping something else to it...It will be the same amount of time as open Authenticator app and select option to wipe the code.

**Comment by AdamVe** [comment]
Sorry for the late response. The development of the app moved to https://github.com/Yubico/yubioath-flutter. One time passwords will become invalid after the defined TOTP time slot passes, so we don’t consider implementation of wiping the clipboard. Please open any new tickets in the new repository.
