### ISSUE TITLE
"Press button for code" not working

### ISSUE THREAD

**Issue by antoinedeschenes** [Yubico/yubioath-android#118]
Hi, 

I can't get codes to show up when requiring touch on Yubico Authenticator 2.2.0 with any YubiKey 5's.

Steps:
-Insert Yubikey
-Authenticator opens up, showing app list with "press button" instead of codes
-Yubikey light is solid green
-Touch button, key LED turns off once, then goes back to solid green
-Code list makes the touch animation
-Codes still show "press button for code"

Phone: 
Pixel 3, Android 10, December security update

So far I've tested those keys:
YubiKey 5 NFC via USB, OATH version 5.2.4
YubiKey 5c, OATH version 5.2.4

I've tried disabling battery optimizations and enabled all permissions, no success so far.

Thanks!

**Comment by imakhalova** [comment]
Hello @antoinedeschenes ,

Thank you for reporting your issue. As I'm reading your repro steps I think there is one step that is missing - you need to select credential that requires touch (tap on credential/account and then touch button on YubiKey).  When you select credential your YubiKey should start blinking which means it expects touch.

Let me know if this helps.

**Comment by antoinedeschenes** [comment]
@imakhalova thanks, looks like this was the issue.
