### ISSUE TITLE
Crash when selecting "scan QR code"

### ISSUE THREAD

**Issue by doctor-owl** [Yubico/yubioath-android#119]
Hey there, I just purchased a Yubikey 5 NFC and I'm having trouble getting the Yubico Authenticator app to work on my Android phone (Samsung Galaxy S9+). Every time I go to add an account and select "scan QR code" the app immediately crashes. I've tried clearing the cache, reinstalling, restarting my phone, etc but no luck so far. Anyone else experience this problem? Any idea how to fix it?

**Comment by imakhalova** [comment]
Are you installing the one from Play Store?
Do you have Google Play services on your phone?

**Comment by marinomeneghel** [comment]
Some logs would be of great help to look into this, any chance you can give a shot to reproducing the issue on a debug build and share the logs?

**Comment by wonderingbookmark** [comment]
Having a similar issue and receive "Camera dependency not yet available, please try again later." 
Version 2.2.0
Android 10, Samsung One UI V2.1
Google Play Services 20.04.14
Any suggestions??

**Comment by AdamVe** [comment]
Sorry for the late response. The development of the app moved to https://github.com/Yubico/yubioath-flutter. We have released a new version of the app, please verify whether the communication issues are still present in the new version and eventually open a new issue in the new repository.
