### ISSUE TITLE
Feature request: Theme follow system default

### ISSUE THREAD

**Issue by igalic** [Yubico/yubioath-android#122]
Following #102, i'd like to also like to suggest that we implement android 10's API which allows apps to read out the current theme preference, and then follow that.

Since this app also implements AMOLED, Tachiyomi has a nice solution to choosing the right darkness:
![Screenshot_20200530-231503](https://user-images.githubusercontent.com/497249/83339182-8dd79c80-a2cb-11ea-8a4c-bd4b99e5a7dd.jpg)

**Comment by AdamVe** [comment]
Sorry for the late response. The development of the app moved to https://github.com/Yubico/yubioath-flutter and released a brand new version of the app (6.0.0) which should follow the phone's theme. Please report any issues in the new repository.
