### ISSUE TITLE
support for otpauth-migration://offline

### ISSUE THREAD

**Issue by Thelvaen** [Yubico/yubioath-android#128]
Please add support for this protocol, as it would allow people to import from other OTP applications, like Google Authenticator.

**Comment by jer-sen** [comment]
Yes ! It would be better than https://github.com/dim13/otpauth

**Comment by AdamVe** [comment]
Sorry for the late response. The development of the app moved to https://github.com/Yubico/yubioath-flutter and we released a new version of the app. Thank you for the suggestion, we will consider it for development in the new version.
