### ISSUE TITLE
Any chance we can get an apk in the releases?

### ISSUE THREAD

**Issue by benoliver999** [Yubico/yubioath-android#13]
I'm in a bit of a loop when I wipe my phone - I need to install yubico to log into google to get to the play store, but I need to log into google to install yubico!

I realise I can build the app, but that's a long winded process and for many users installing the SDK and maven is a lot just for one app!

**Comment by dainnilsson** [comment]
You can get the APK from F-Droid: https://f-droid.org/repository/browse/?fdfilter=yubico+authenticator&fdid=com.yubico.yubioath

There's a download link there, so you don't need to install any other app first. If that doesn't suit your needs, feel free to reopen this issue and let us know what's missing!
