### ISSUE TITLE
Feature Request: Support Yubico Authenticator on Chromebooks with USB-C

### ISSUE THREAD

**Issue by ASMailer** [Yubico/yubioath-android#130]
Need USB-C support in the authentication app on Chromebooks as most of them don't have NFC. Otherwise the FIDO cannot be used at the moment. Some users try to get the linux desktop app to run in the linux subsystem, but here there are challenges to be able to use the USB interfaces at all.

**Comment by dainnilsson** [comment]
Unfortunately the same (or at least similar) issues prevent Android apps from accessing USB devices on ChromeOS. See #60 for more details, closing as duplicate.
