### ISSUE TITLE
Yubico Authenticator not recognizing Yubikey 5C Nano on Chromebook Android 

### ISSUE THREAD

**Issue by Elliander** [Yubico/yubioath-android#131]
I purchased Yubikey 5C Nano specifically to be used with my Samsung Chromebook Pro. It fully supports Android, so I installed Yubico Authenticator and then proceeded to add a new credential manually. I'm not using QR codes because this setup wouldn't support that. When I click save it says:

"Tap or insert your Yubikey"

The lights do not come on, which would indicate that it is ready to accept a tap. If I tap it myself the two lights do come in indicating that my touch is recognized by the device, but the app does not recognize that I tapped it at all. Unplugging it and plugging it back in doesn't help. I checked Android app permissions and it doesn't seem to need any special permissions, aside for access to the camera which I did grant.

It appears to be the case that the Yubico Authenticator does not recognize the Yubikey 5C Nano when it is in a Chromebook running Android. Is there any way to make it recognize it?

**Comment by dainnilsson** [comment]
See #60. Unfortunately, while ChromeOS does support running Android applications, it does not support them using USB nor NFC APIs, making the app rather useless.

**Comment by Elliander** [comment]
Hold on. That's not true at all! My Chromebook apps are fully capable of actually using USB devices, including webcam, video capture devices, and flash drives. This has been true since 2018.

https://www.xda-developers.com/chrome-os-android-apps-usb-drive/

You shouldn't close an issue for something like this.

**Comment by dainnilsson** [comment]
This issue was closed as it is a duplicate of the one I linked (#60). In it, you can see that the issue has been investigated.
