### ISSUE TITLE
NFC Error in YubiKey communication

### ISSUE THREAD

**Issue by thechubbypanda** [Yubico/yubioath-android#136]
- Yubico Authenticator version: 2.2.0
- Operating system and version: Android 10 (Note 9)
- YubiKey model and version: 5 NFC
- Bug description summary: Authenticator app does not recognize key

Steps to reproduce
---

Hold key on NFC reader location while app is open

Expected result
---

App authenticates key

Actual results
---

Error toast message

**Comment by florianajir** [comment]
+1

**Comment by jeantil** [comment]
related to https://github.com/Yubico/yubioath-android/issues/127

**Comment by werd4311** [comment]
Any progress on this issue? 

It's pretty obvious from the one-star play store app reviews at this point that it simply doesn't work at all with current Android devices. This is not an isolated issue.

**Comment by banderson5144** [comment]
Just bought a YubiKey 5 NFC yesterday and I am seeing this issue on a Pixel 6 Pro. It works when I put it in the USB C port, but NFC tap says Error in YubiKey Communication

**Comment by AdamVe** [comment]
Hi everyone, we are sorry to hear you have issues with your Yubikeys and the NFC functionality in Yubico Authenticator. The version 2.2.0 should be compatible with Android versions 4.4 to 12 and the NFC communication should be working if the device supports it.

Here are some general tips for using Yubikeys and NFC:

- know where the NFC antenna is located in the device and tap the key at that place (For Pixel 6 Pro, the antenna is just below the G logo, see here: https://support.google.com/pixelphone/answer/7157629?hl=en#zippy=%2Cpixel-pro)

 - hold your Yubikey as close to the NFC antenna until your phone vibrates
 - if you use any phone case, try also without if it makes difference
 - if you have a chance, see if NFC works with a different tag or phone
 - try to read your Yubikey with a NFC tag reader app

If you still have troubles with NFC, please add an adb logcat message to this conversation.

**Comment by banderson5144** [comment]
@AdamVe so when I tap it with or without the case on and don't have the Yubico Authenticator app open, it opens up Chrome to the Yubico validation website.

Also when I use the NXP TagInfo app, it is able to read the entire contents of the YubiKey.

However, it is only when I open the Yubico Authenticator app is where I have the Error in communication problem.

For the adb logcat you are requesting, do I just hook it up to my computer and run that command from the CLI? (Please provide an example if you can)

**Comment by banderson5144** [comment]
I am also experiencing the same issue on a Pixel 2XL

**Comment by AdamVe** [comment]
Hi and thank you for the updated information! Let's see if we get any info with the logcat. It needs a bit of setup on you machine though.

1. install the needed tools on your machine (https://developer.android.com/studio#command-tools)
2. connect the phone with with usb cable (if you are on Android 11+ you can also setup Wifi connection) and enable the Developer Options -> USB Debugging / Wireless debugging
3. run abd logcat in your shell, and you should see all the phone is logging
4. reproduce the issue with Yubikey and stop the adb logcat command. see if you can find any error close to the output related to nfc, yubioath or yubikey

You can find information about how to install the tools in this page: https://developer.android.com/studio/command-line. More information about logcat: https://developer.android.com/studio/command-line/logcat

> I am also experiencing the same issue on a Pixel 2XL

Could you, please share the Android version of the Pixel 6 Pro as well as the Pixel 2 XL.

**Comment by banderson5144** [comment]
Here is the logcat https://pastebin.com/c9w7YcEv (had to put it there since I couldn't paste the entire log)

I ran this on my Pixel 2XL. It is running Android 11 Build Number RP1A.201005.004.A1

**Comment by AdamVe** [comment]
Thanks! Could you check the app settings and turn off "Read NFC NDEF payload" option? If that option is not enabled for you, enable and disable it. 

Then try to tap with the key again. Does it make any difference?

I ask for this as your logcat shows following error several times; that part is executed only if you have the settings option enabled.
```
E yubioath: Error reading NDEF tag.
```

**Comment by banderson5144** [comment]
![PXL_20220201_151123586.jpg](https://user-images.githubusercontent.com/2395774/151994948-3cbd87e7-0ec8-435c-bbcc-21ac2faf3ff2.jpg)

I get this, but this doesn't look like the screen when I plug it in via USB

**Comment by AdamVe** [comment]
The screen you see is showing an Yubico OTP (one-time password) code which was read through the NFC. If you had OATH codes stored in the key, they would show up under the NFC item:

<img src="https://user-images.githubusercontent.com/1954891/151998244-b0dd469d-3af9-4978-8744-93a2106b09f5.jpg" width="120" />

The NFC/NDEF item you see will be visible only you have have the option "Read NFC NDEF payload" enabled in settings.

Do you still get the "Error in YubiKey Communication" when using NFC?

**Comment by banderson5144** [comment]
No I don't get that error. So this means it is working as expected yes?

**Comment by AdamVe** [comment]
Yes. You should be able to add new TOTP/HOTP codes with the blue plus button. The codes will be securely stored in the key and will be available through USB connection as well. You will be able to see them also in the desktop app.
