### ISSUE TITLE
Devices without NFC shouldn't prompt to tap YubiKey

### ISSUE THREAD

**Issue by hmmwhatsthisdo** [Yubico/yubioath-android#138]
This one is probably a bit superfluous, but for those with a lot of devices (where not all have NFC) it would be nice if the "tap or insert your YubiKey" prompt read just "Insert your YubiKey" on devices where NFC isn't available.

**Comment by AdamVe** [comment]
Sorry for the late response. The development of the app moved to https://github.com/Yubico/yubioath-flutter and a new version 6.0.0 has been released. Thank you for the suggestion, we will consider this for updates in the new version.
