### ISSUE TITLE
Feature request: Configurable password & list cache time

### ISSUE THREAD

**Issue by TechupBusiness** [Yubico/yubioath-android#139]
I use a password protection for my 2FA codes, but everytime I want to use the app I need to tap up to 3 times and also enter the password to show the code in the application. Would be great if I could configure the cache time for the password and the code list. For example as long as I dont use another Yubikey, it could store all entries. And the password could be cached for e.g. 1h, 6h, 1day or even more complex: as long as I'm connected to the current WLAN (so as soon as the device leaves my home or office the password will be required again).

**Comment by AdamVe** [comment]
Sorry for the late response. The development of the app moved to https://github.com/Yubico/yubioath-flutter. We have also released a new version of the app (6.0.0). Could you please open a new issue, if this is still relevant for you, in the new repository?
