### ISSUE TITLE
Yubico Authenticator is no longer on the Play Store

### ISSUE THREAD

**Issue by JasonKraft** [Yubico/yubioath-android#143]
Title is self-explanatory. The app is missing from the Google Play Store.

**Comment by dainnilsson** [comment]
The app unfortunately got removed yesterday due to a problem with the Play Store listing, we resubmitted immediately and are currently `In review`. Hopefully back soon!

**Comment by floviolleau** [comment]
Hi,

I don't see neither yubiclip

**Comment by dainnilsson** [comment]
Same issue there, also currently `In review`.

**Comment by dainnilsson** [comment]
Small update: Unfortunately our re-submission got rejected in the review yesterday due to the link to our privacy policy being wrong (it was pointing to an outdated URL). We immediately fixed the link and re-submitted again, but we are now (still) waiting `In review`...

**Comment by dainnilsson** [comment]
...and we're back! The reviews (both Yubico Authenticator and YubiClip) have now been completed, and both are back in the Play Store. I'll leave this issue open until Monday or so in case it takes time to propagate, but everything should now be resolved.
