### ISSUE TITLE
So what's the status of this app?

### ISSUE THREAD

**Issue by ghost** [Yubico/yubioath-android#147]
I'm genuinely curious as to where all the development has gone to this app. It's highly outdated with half a decade-old dependencies all over the place, pointless build configurations and you're not even using the latest versions of your own SDKs and  libraries (yubikit-android, etc) and using extremely old beta versions of your own stuff.

The app on Play Store hasn't been updated since September 2019 and the only reason it's still up is because of weak Google Play enforcements like targeting SDK 29 which is the _bare_ minimum allowed. You're supposed to be targeting SDK 30 now and you cannot release a new update until you do so. Which in turn, leaves the app decaying with more older dependencies and targeting newer SDKs will require code changes so gives you more of a reason to unnecessarily put off the app's development. 

You have tons of 1-star negative reviews on the Play Store because of lack of app updates and development. People have reported tons of issues with your app not working on their devices, especially ones with problematic NFC radios which can be compensated for in the code, unreliable reading even by USB, and much more if you could simply go through your own reviews. These are also very new reviews too ~2021.

I'm fairly certain you're only updating the iOS app because Apple is more restrictive and has better quality control here.

So what's the status of this app? Are you accepting PRs? Will contributors be paid for stuff like this?

**Comment by dainnilsson** [comment]
I understand your frustration. It is as you say, this app hasn't received much attention lately. It's been an issue of resources and prioritization for us. We've both been short-staffed when it comes to Android development, and had things that seemed more urgent at the time to deal with. We ARE changing this. We are now actively working on development to refresh this app, both to update the UI but also to build it on top of our Android SDK, and to take into account various lessons learned from our iOS and desktop versions. While I can't commit to a release date of this next version right now, we do expect it to be later this year.

In the meantime, we will continue to address any serious issues with the current version of the app. The specific NFC issue is unfortunately one we cannot do much about. There aren't really very many settings to tweak here: We use the API as provided by the platform. What we've seen is that the quality of NFC varies vastly from device to device (both in terms of hardware, like antenna, and the software stack). On some handsets this is very unreliable, and there is a very specific "sweet spot" where the YubiKey has to be held just right. Most of the time it does take some practice, but can be used quite reliably after that. It is a stumbling point for many, I'm sure.

To answer your specific questions: We may accept PRs, but are not looking for any big changes at this point and are unlikely to make a new App Store release unless we have to, until we complete the work on the refresh of the app. We are also not offering any payment for external code contribution.

**Comment by eukislov** [comment]
> 

Maybe there is some news about the updated application for Android? Estimated release dates?

**Comment by eukislov** [comment]
> I understand your frustration. It is as you say, this app hasn't received much attention lately. It's been an issue of resources and prioritization for us. We've both been short-staffed when it comes to Android development, and had things that seemed more urgent at the time to deal with. We ARE changing this. We are now actively working on development to refresh this app, both to update the UI but also to build it on top of our Android SDK, and to take into account various lessons learned from our iOS and desktop versions. While I can't commit to a release date of this next version right now, we do expect it to be later this year.
> 
> In the meantime, we will continue to address any serious issues with the current version of the app. The specific NFC issue is unfortunately one we cannot do much about. There aren't really very many settings to tweak here: We use the API as provided by the platform. What we've seen is that the quality of NFC varies vastly from device to device (both in terms of hardware, like antenna, and the software stack). On some handsets this is very unreliable, and there is a very specific "sweet spot" where the YubiKey has to be held just right. Most of the time it does take some practice, but can be used quite reliably after that. It is a stumbling point for many, I'm sure.
> 
> To answer your specific questions: We may accept PRs, but are not looking for any big changes at this point and are unlikely to make a new App Store release unless we have to, until we complete the work on the refresh of the app. We are also not offering any payment for external code contribution.

Maybe there is some news about the updated application for Android? Estimated release dates?

**Comment by dainnilsson** [comment]
> Maybe there is some news about the updated application for Android? Estimated release dates?

There's a blog post that has some news related to this here: https://www.yubico.com/blog/introducing-yubico-authenticator-6-for-desktop/
The current status is that the new app is currently being developed for both desktop and Android. I don't have any dates to share right now, but we hope to have a public beta for Android ready to go fairly soon, and to release the stable versions (desktop and Android) a bit later this year.

**Comment by AdamVe** [comment]
The development of the app moved to https://github.com/Yubico/yubioath-flutter and we have released a new version of Yubico Authenticator for Android (6.0.0). We are looking forward to your feedback in the new repository.
