### ISSUE TITLE
Request feature OATH password timeout custom setting, clear list accounts from dialog

### ISSUE THREAD

**Issue by photographer-mememe** [Yubico/yubioath-android#150]
The OATH password seems to clear from the app after some unknown time (seems to be between 3 to 5 minutes?). Then the password must be entered again.

It may be convenient to have an option to be able to set the exact amount of time from the settings menu. I prefer setting a shorter time.

Also, the list of account names persists in the dialog when using the NFC, until the app is forced closed or swiped away from the recent apps list. If the app remains in the background, the account names do not go away. It would be better if the names were cleared at the same time as password timeout. For example, the desktop app will clear the dialog when the Yubikey is unplugged from USB. (When using USB on android, unplugging will clear the list)

**Comment by AdamVe** [comment]
Sorry for the late response. The development of the app moved to https://github.com/Yubico/yubioath-flutter. Yubico Authenticator for Android 6.0.0 now clears accounts read from NFC keys after inactivity. Please provide your feedback and suggestions in the new repository.
