### ISSUE TITLE
Feature Request: Sync and/or transfer accounts

### ISSUE THREAD

**Issue by Chantology** [Yubico/yubioath-android#154]
If I buy a new backup phone and I want to transfer the authentication codes to another device. For now I have to either reset the 2FA and do it again with all devices or enter the code in case I wrote it down. Other tools are able to sync between devices. 

Is this even wanted by design because this could mean less security?

**Comment by AdamVe** [comment]
Hi, please have in mind that the Android application does not store any credentials (TOTP/HOTP codes) - they are stored only in the YubiKey and the application is used to add/show/edit/delete them from the YubiKey.

That means, when you install the Android Authenticator to a new device, it will show the credentials for any YubiKey, there is no data to transfer from the old phone to the new one.

**Comment by Chantology** [comment]
thank you very much for the reply. So it means basically if I want to transfer the codes across devices I need to connect the Yubikey to the new device, right?

**Comment by AdamVe** [comment]
You don't need to transfer any codes, they are not in the phone, they are in the YubiKey.

Having a YubiKey, you can use any mobile device or desktop computer with our open-source apps  to access and manage those codes. You can get a good summary in this page:  https://www.yubico.com/products/yubico-authenticator/
