### ISSUE TITLE
Choosing to "always" launch yubico authenticator on NFC swipe is disregarded

### ISSUE THREAD

**Issue by mittwinter** [Yubico/yubioath-android#19]
Hey,

I really like the new functionality to automatically launch the Yubico Authenticator on NFC swipe as introduced by issue #5. However, if I choose to perform this "Always" (instead of "Just once"), it is disregarded. On the next swipe, I'm presented with the dialog "Complete action using" again, with Firefox, YubiClip and the Authenticator to choose from.

Would be nice if this could be fixed.

**Comment by dainnilsson** [comment]
Unfortunately this is something that is out of the hands of the app. For me it works, but I've had the same problem you describe with other apps. I'm not sure what causes it, but it seems to be an issue with how Android handles preferred apps.
