### ISSUE TITLE
Cannot authenticate Amazon AWS

### ISSUE THREAD

**Issue by cboettig** [Yubico/yubioath-android#20]
Thanks for providing such awesome products in the Yubico Neo key and Yubico Authenticator App. For the most part it has been seamless to get set up.  However, I am not having any luck setting up authentication for Amazon AWS multi-factor authentication.  It looks like hardware authentication is only supported using hardware devices purchased directly through them, which is a shame as I have no desire to carry an additional secure device.  Therefore I'm trying to enable the Yubico Authenticator App to act as my virtual multifactor authentication device.  The Yubico Authenticator app has worked beautifully for me on other platforms (e.g. GitHub ;-)), but no luck with AWS.

After scanning the QR code, the AWS virtual MFA setup asks me enter "two consecutive keys".  I enter the key that originally appears after I scan the code and touch my Yubico key to my Android phone.  I then wait until the timeout finishes and touch the key again to get a second code, and enter that as well. However, I always just get a: " Failed to associate the token " error.  Have you tested this with AES before?  Any idea what is going wrong?

**Comment by cboettig** [comment]
Hmm, a few more tries seems to have done the trick.  Perhaps it is just necessary to enter the 'consecutive' numbers rather quickly in succession?  Requiring two keys to verify the setup this way makes things rather tricky.  

Perhaps the app could do something to facilitate this process (e.g. generate both consecutive keys automatically for sign up?)  Anyway, glad it appears to all be working now.

**Comment by minisu** [comment]
Thanks for reporting. We'll close this for now since you got it working. I think that we'll not implement any specific feature for this, at least not unless we hear about more sites using this methodology.
