### ISSUE TITLE
RFE: allow changing of credential name

### ISSUE THREAD

**Issue by cdmackay** [Yubico/yubioath-android#24]
Please consider adding the ability to change the name of a previously-added credential.

This is the only thing that can be done in the Google Authenticator OATH app that cannot be done in the Yubico app.

It is very handy to be able to do this. e.g. I add a new service, for a remote SSH login to  a server on a remote site which uses pam_google_authenticator. Since there is only one system at the remote site, I call it "site1".

A few months later, I add another service for a different server at that site. I would like to rename my existing "site1" to "site1-serverA", so I can now add "site1-serverB".

thanks much indeed.

I am assuming here that it is actually possible to write a new name to the credential on the key, of course.

**Comment by cdmackay** [comment]
oh, and Chris in Support said he likes the idea too :)

**Comment by dainnilsson** [comment]
There's unfortunately no way to do this as it's not a function that is available from the YubiKey. You can write, delete and use credentials, but not modify them.
