### ISSUE TITLE
Open Yubico Authenticator App with NFC tap

### ISSUE THREAD

**Issue by vo5tr0** [Yubico/yubioath-android#26]
Hey,
since the update to Android Marshmallow on my Nexus 6 the authenticator app doesn't start automatically after I tap my phone on my Yubikey Neo. Instead of that it opens my browser on https://my.cubico.com/neo/*keyofmyyubikey*
I also tried to reinstall the app, but no difference..

best regards

Julian

**Comment by dainnilsson** [comment]
It works for me (Nexus 6, Android 6.0). If you go into settings (of the OS, not the app), apps, then find the entry for Yubico Authenticator, there's an "Open by default" item in the menu. Mine has "some defaults set". If I click on it under "Other defaults" I have "You've chosen to launch this app by default for some actions.". Does yours show anything different?

**Comment by dainnilsson** [comment]
Nevermind, I've been able to reproduce it with a clean install, as well as fix it. Look for a new release in the coming days.

**Comment by vo5tr0** [comment]
Sorry, i fogot answering you. I was able to open the app by deactivating Open by default in google chrome. It is not the best solution, but it works. I am looking forward to you update. :)

**Comment by dainnilsson** [comment]
Ah, so that's what's keeping the prompt from showing up, good to know!

The update just makes it easier to select Yubico Authenticator to be used every time from within the system settings, so it's not much better I'm afraid.

**Comment by dainnilsson** [comment]
Ok, new version of the app is out now (1.0.3), which uses "App Links Verification" (http://developer.android.com/training/app-links/index.html). It will still keep using Chrome (or other browser) if it is set to always open all URLs, which it seems to be by default for some reason (at least I don't recall changing this myself). Anyway, it should be an improvement.
