### ISSUE TITLE
Unable to view codes since updating to version 1.0.3

### ISSUE THREAD

**Issue by iDJH** [Yubico/yubioath-android#27]
Since updating to version 1.0.3 (versionCode 26) of Yubico Authenticator via Google Play I can no longer view codes stored on my YubiKey NEO. I enable NFC as usual and tap the YubiKey to my device, the Yubico Authenticator app opens but displays "Tap your YubiKey NEO to view credentials".

Reverting to version 1.0.2 fixes the problem.

My device is a HTC One M8s running stock Android 5.0.2.

**Comment by Franzaine** [comment]
@iDJH Does it work if you tap your YubiKey with the app open?

**Comment by iDJH** [comment]
Yes it does work if I manually open the app first and then tap the YubiKey.

I should have tried this, but I am used to the app just opening when I tap.

**Comment by petter-fidesmo** [comment]
I think this was borken by the last PR, will provide a fix.

**Comment by petter-fidesmo** [comment]
There is a PR (#28) for this now.

**Comment by dainnilsson** [comment]
PR has been merged, confirmed working. The next release will include it.
