### ISSUE TITLE
Support non-NFC devices/yubikeys via USB OTG

### ISSUE THREAD

**Issue by stp-ip** [Yubico/yubioath-android#30]
Support USB OTG to enable TOTP on non NFC enabled devices and non NFC enabled yubikeys.

**Comment by liljenstolpe** [comment]
This becomes really important when I now have to use a 4c instead of my neo due to the new laptop, but then can't use yubiauth on my nexus5x.  Help!

**Comment by dainnilsson** [comment]
This is pretty high on the priority list. Unfortunately I can't currently give an estimate for when the next version of the app will be out, but we'll definitely investigate adding this functionality for it.

**Comment by chipironcin** [comment]
+1

**Comment by stp-ip** [comment]
Any update or ETA?

**Comment by Garrett-M** [comment]
+1. This is pretty vital with the 4c

**Comment by dainnilsson** [comment]
Not much in terms of an update, there's still no ETA for a release and it's still a top priority for this project. Work on this feature has started, however, so progress being made.

**Comment by chipironcin** [comment]
Anything we can help with to push this further? It is a super cool feature!

**Comment by dainnilsson** [comment]
I've just released a beta (you will need to opt-in here: https://play.google.com/apps/testing/com.yubico.yubioath, or use the attached APK directly).
[yubioath-desktop-1.2.0-beta1.apk.zip](https://github.com/Yubico/yubioath-android/files/946616/yubioath-desktop-1.2.0-beta1.apk.zip)

The UX still needs work, but the functionality is all there. Note that your Android device will require USB Host support, which not all devices do. The devices I've tested successfully are:

- Google Pixel (with a YubiKey 4C connected directly, as well as a YubiKey NEO via USB A to C adapter)
- Samsung Galaxy Alpha (YubiKey NEO using a USB OTG cable)

Known issues:
- When adding a new credential via QR code to a USB device, the prompt to edit the credential name is only flashed briefly, not letting you change the name, before it is written. Workaround: Either stick with the default name, or add the credential using the desktop Yubico Authenticator.

**Comment by chipironcin** [comment]
That's awesome! Thanks for the beta!
I cannot wait to try it out during the weekend and give you feedback.
Also, I have some knowledge developing Android apps, I may be able to help with UX if you have a branch or PR ;)

**Comment by sdaugherty** [comment]
attempted it on an alcatel onetouch pop astro, and the app just complains
that no NFC is available and refuses to launch.

**Comment by dainnilsson** [comment]
@sdaugherty And I take it the phone lacks NFC? If so that's expected at this point, as the app still "thinks" it needs NFC. I'll add that to the list of known issues above!

**Comment by sdaugherty** [comment]
@dainnilsson  that's correct, it's a device without NFC.

**Comment by dainnilsson** [comment]
@sdaugherty thanks, I'll make sure the final version works without NFC!

**Comment by liljenstolpe** [comment]
I just tried the beta by setting up as a new google authenticator for a google account.  Scanned the QR.  However, the code being generated is not matching what google was expecting.

**Comment by dainnilsson** [comment]
@liljenstolpe Thanks, I can confirm that there's something up with adding new credentials that doesn't seem to work. Adding the credential via QR code or manual input both seem to be affected by this. I'll investigate the issue further on Monday. A workaround for now is to add new credentials by using the PC version, or the stable 1.1.0 (assuming you have a NEO with NFC or a PC with a USB-C port that is).

**Comment by dainnilsson** [comment]
I've now uploaded beta-3 to Google Play, which fixes the credential writing issue (@liljenstolpe), and although I can't confirm it works as I don't have access to an Android device without NFC, I believe it should run on such a device (@sdaugherty, if you can confirm that it works that would be great).

[yubioath-android-1.2.0-beta3.apk.zip](https://github.com/Yubico/yubioath-android/files/950738/yubioath-android-1.2.0-beta3.apk.zip)

**Comment by liljenstolpe** [comment]
@dainnilsson Confirm that the new beta works.  Thx!

**Comment by sdaugherty** [comment]
can no longer test with the device I was originally trying to use, but on a
asus zenfone 3 max, which lacks NFC, it now will connect my yubikey neo via
OTG

**Comment by dainnilsson** [comment]
Thanks everyone for testing! I've now made a 1.2.0 release (available from the releases tab here on Github, and being pushed to the beta channel on Google Play). Unless any major issues are found with it, I'll promote it to "stable" in the Play store in a few days. Feel free to open new issues for any problems you find with it.

**Comment by michaelblyons** [comment]
Just to confirm, is [this KB article][1] correct if this issue is closed? Its last-modified date is a few days after @dainnilsson's last post.

[1]: https://www.yubico.com/support/knowledge-base/categories/articles/can-yubikey-4c-plugged-directly-android-phones-tablets-usb-c-ports/

**Comment by dainnilsson** [comment]
That KB article is incorrect, kind of :)

The current stable version of Yubico Authenticator for Android supports USB (including directly connecting the YubiKey 4C to your phone) on an experimental basis. The current beta version (2.0.0 alpha) has more full-blown support, but hasn't yet been released as stable. Thanks for pointing it out, I'll make sure to get that article updated once the new (2.0) version of Yubico Authenticator is released as stable!

**Comment by posix4e** [comment]
How does one use it. It doesn't seem to work on my chromebook

**Comment by slimmtl** [comment]
It does not work on my oppo f7 Android 8: no NFC, it asks to tap

**Comment by Blaster1920** [comment]
Any updates? +1
