### ISSUE TITLE
Broken on Marshmallow / CM13

### ISSUE THREAD

**Issue by saschpe** [Yubico/yubioath-android#32]
Not quite sure if it's only related to Android M or CyanogenMod 13. However, the NEO isn't discovered anymore (other NFC labels work like a charm).

**Comment by platypus5021** [comment]
Same issue. OnePlus One on Android 6.0 (Marshmallow) with CM13. Worked on CM12.1.

**Comment by dainnilsson** [comment]
Can either of you try the 1.0.2 version of the app? (You can get it from here: https://developers.yubico.com/yubioath-android/Releases/). Version 1.0.3 introduced the Nordpol library for NFC communication (see #23) and it would be good to know if that has anything to do with this problem or not.

**Comment by jawilson** [comment]
I'm having the same issue on my LG G3 running the official cm-13.0-20151207-NIGHTLY-vs985. I tried 1.0.2 with no luck. If a logcat or anything else would be helpful, please let me know.

**Comment by saschpe** [comment]
So I tried 1.0.2 from f-droid.org to no avail. I assume it's a CM13 issue. I'll double-check with a Nexus6 + M (Google image) tomorrow.

**Comment by jawilson** [comment]
I'm fairly certain this is a CM13 issue. I've created a JIRA ticket [here](https://jira.cyanogenmod.org/browse/NIGHTLIES-2103).

**Comment by dainnilsson** [comment]
Looks like a CM13 issue, indeed. Please re-open if something comes up that points to anything that can be done in this app to fix this. Closing for now...
