### ISSUE TITLE
Feature request: ability to edit accounts

### ISSUE THREAD

**Issue by rmenessec** [Yubico/yubioath-android#33]
It would be great if we could get the ability to edit account entries on long-press, instead of just the ability to delete entries. Confirmation before deleting entries would be useful, too.

**Comment by dainnilsson** [comment]
Unfortunately that isn't possible as it would require hardware support for modifying credentials, which doesn't exist.

**Comment by rmenessec** [comment]
To be clear: it's not even possible to edit the name after the fact? If it is, I'd like that at a minimum.

Thanks!

**Comment by dainnilsson** [comment]
No, it is not. The only change that can be made to a stored credential is to delete it.
