### ISSUE TITLE
Should case insenitively compare the algorithim parameter in OTP URI in QR codes

### ISSUE THREAD

**Issue by evaryont** [Yubico/yubioath-android#37]
I've set up my own FreeIPA instance and tried to add an OTP token to my account within. However, whenever I try to scan the barcode generated, Yubioath pops up with an invalid URI error. Looking at the source code and the URI FreeIPA generated, I think it's because the application expects algorithim to be `SHA1` or `SHA256` while FreeIPA generates the url with algorithim set to either `sha1` or `sha256`. Since it's lowercase instead of uppercase as the application expects, an error is thrown.

Also, FreeIPA provides the option of using SHA384 and SHA512. Is it feesible to include those as well in Yubioath?

**Comment by dainnilsson** [comment]
You may want to open an issue against FreeIPA, as the otpauth URI specification specifies that uppercase should be used (see: https://github.com/google/google-authenticator/wiki/Key-Uri-Format). I don't see any problem with supporting lowercase as well though, so I'll add that.

It's not possible to add support for new algorithms without a firmware change to the YubiKey (and thus would only be available for new keys). If we see a large demand for an unsupported algorithm we will consider adding it.
