### ISSUE TITLE
Allow adding icons to accounts

### ISSUE THREAD

**Issue by radeksimko** [Yubico/yubioath-android#38]
If user has a long list of accounts and is fortunate enough that they remembered to add a unique service name (that's what comes in front of the colon in account name, e.g. in `Google:radek.simko@gmail.com` it's `Google`) as not all QR codes are descriptive enough, it may still consume quite significant brain capacity to find the right row in a long list.

I believe that adding icon to at least differentiate services would help the UX a lot.

---

Thanks for all the good work on this app and Yubikey!

**Comment by gene1wood** [comment]
You might be able to use the [FreeOTP](https://fedorahosted.org/freeotp/browser/android/app/src/main/java/org/fedorahosted/freeotp?order=name) open source code as a basis for this feature as they support icons.

**Comment by nagromc** [comment]
Please note that [FreeOTP](https://github.com/freeotp/freeotp-android) has [`INTERNET` permission](https://github.com/freeotp/freeotp-android/blob/9ee5a2bbbb2e8c77884f4066a50375fd4f57cdcc/app/src/main/AndroidManifest.xml#L40). It could lead to security flaws as in the [comment](https://github.com/freeotp/freeotp-android/issues/75#issuecomment-281943843) I dropped.

If anyone wishes to import some code from FreeOTP, be careful to **not** give [`INTERNET`](https://developer.android.com/reference/android/Manifest.permission.html#INTERNET) permission, or any other external access such as [`BLUETOOTH`](https://developer.android.com/reference/android/Manifest.permission.html#BLUETOOTH) or [`WRITE_EXTERNAL_STORAGE`](https://developer.android.com/reference/android/Manifest.permission.html#WRITE_EXTERNAL_STORAGE). Import icons within the app instead.

**Comment by dainnilsson** [comment]
Just adding a note here to say that while the feature hasn't (yet) been added, the UI has been re-designed to help differentiate between multiple credentials visually, and to better accommodate adding this feature in the future in the 2.0.0-alpha1 release. You can get it from the releases page here on Github, or by signing up for beta releases on the Google Play Store page for the app.

**Comment by edent** [comment]
I can't see a way to add icons to the new app. I tried both Facebook and Github - neither added an icon automatically.

It might help to take some UI "inspiration" from Authy.  They use icons, and the site's primary colour to help differentiate between accounts.

![authy vs yubico](https://user-images.githubusercontent.com/837136/31576442-df922702-b0f2-11e7-95f3-0d45238cdecf.png)

The layout is also a lot more helpful if you have many accounts.

**Comment by dainnilsson** [comment]
> I can't see a way to add icons to the new app. I tried both Facebook and Github - neither added an icon automatically.

Yeah, that's because the feature hasn't yet been implemented, hence this issue being open ;)

But I do have some news! I've just pushed a commit that introduces basic support for icons. Here's a teaser:
![image](https://user-images.githubusercontent.com/140781/31778775-c6a9ed76-b4f1-11e7-9f5b-ae9da6beabff.png)

**Comment by edent** [comment]
You tease! Love it 😁

**Comment by dainnilsson** [comment]
Ok, just released alpha2 with this feature!

**Instructions:**
1. Select a credential by long-pressing, or tapping the icon.
2. Tap the "image" icon in the top menu bar.
3. Select an image from your phone to use for the credential.

Right now you set the icon for each credential. I thought about having one icon per issuer first, but figured that you might want to have different icons for the same issue to differentiate different accounts.
You also have to find icons yourself. Google image search works pretty well for that I've found.
