### ISSUE TITLE
Add support for manual input of key

### ISSUE THREAD

**Issue by sjvs** [Yubico/yubioath-android#4]
Hi,

Great app! I received my Neo today and started using this straight away. I am used to keeping my secret keys for 2FA (Google Authenticator) in a safe deposit box, just in case I lose my phone. Google Authenticator has support for manually entering keys (ie, without scanning a barcode). It'd be great if there would be a way to manually enter a key again after losing my Neo. Or is there something I'm overseeing that makes this impossible?

Thanks!

  Bas

**Comment by jtyr** [comment]
This issue should be fixed by merging the Pull Request #12.

**Comment by dainnilsson** [comment]
This issue has been fixed.
