### ISSUE TITLE
Launch Yubikey Authenticator on NFC tap

### ISSUE THREAD

**Issue by ekelly** [Yubico/yubioath-android#45]
It would be fantastic if the authenticator automatically opened when you tapped the Yubikey to the phone. Currently, I have to exit what I'm currently doing, navigate to the tiny icon on my home screen, open it, then tap. The one-time tap would be so much more convenient.

**Comment by gene1wood** [comment]
I'm running version 1.1.0 on my Android 5.1 phone and when I touch my yubikey to to the phone it launches the app regardless of what app is currently running on the phone. The same thing is true for an app I have that reads the available balance on an NFC public transit card.

@ekelly do you have any other NFC apps on your phone? The issue might be with your nfc config or your phone if the same problem happens with other types of nfc devices and other nfc apps.

**Comment by ekelly** [comment]
Sorry, I should have closed this issue. It didn't work the first few times
I tried it, but it's working for me now.

**Comment by SturmB** [comment]
I apologize for resurrecting a dead and closed thread, but this has now become an issue for me, as well. I didn't have any trouble with my previous phone (a Google Nexus 6), but I recently upgraded to a Samsung Galaxy Note 8 and now the Yubikey Neo I have does not launch Yubico Authenticator. Instead, it always launches Samsung Internet and navigates to "my.yubico.com/[some-long-string-here]", giving me a "CONGRATULATIONS!" message, which is useless to me.

I have tried clearing the defaults for Yubico Authenticator in the phone's settings, so that the next time I tap the Neo to the phone, it asks what I want to launch. I tell it to Always launch Yubico Authenticator, which it does, but if I then close the app and try again, it goes back to launching Samsung Internet again. (And that isn't even set as my default web browser on this device, either!)

What can I do to force the phone to always launch Yubico Authenticator (instead of Samsung Internet) when I tap my Yubikey Neo to it?

**Comment by dainnilsson** [comment]
Try this (note that I'm not very familiar with TouchWiz, the Samsung interface, so the steps might be slightly different on your phone):

1. Open the system settings of your phone, then select Apps & Notifications
2. Select "See all ... apps" to get a list of all installed apps, then find Yubico Authenticator and tap it.
3. Tap on "Open by default"
4. Tap on "Open supported links" and change it to "Open in this app".

Hopefully that setting will stick.

**Comment by SturmB** [comment]
Wow, thanks for the incredibly fast reply, @dainnilsson!

Unfortunately, your suggestion is something I've already tried. In TouchWiz's settings, I go to Apps -> Yubico Authenticator, then tap the only thing that seems appropriate in the list: "Set as default". This takes me to another screen where I can clear the defaults (It currently states that "This app is set to open by default for some actions") and choose the app links. For the latter, I can choose to go to supported URLs "In this app", "In other app", or "Always ask". I have "In this app" already chosen. And the list of supported web addresses only has one item in the list (and cannot be changed): "my.yubico.com".

So, if it's already set as default, set to be opened in this app, and to do so for the "my.yubico.com" web address, then why on earth is it not following those rules? I don't doubt that it's some strangeness with Samsung, but I am actually really liking TouchWiz and would hate to have to use a different launcher (_if_ that would even change things).

**Comment by dainnilsson** [comment]
Sounds to me like "some strangeness with Samsung" seems likely, not that that helps you much unfortunately. How did you install Yubico Authenticator? From the Play store or somewhere else?

**Comment by SturmB** [comment]
That's correct. It was originally downloaded from the Google Play store on my Nexus 6 long ago. When I got this new device a few weeks ago, I used the Samsung Smart Switch app to transfer over all of my content (including apps) from the Nexus 6 to the Note 8. (Took almost all day, too.)

**Comment by dainnilsson** [comment]
And is it the new beta version with the white/green color scheme, or the older dark one?

**Comment by SturmB** [comment]
Didn't know there was a new beta version. This is still the dark-themed one. (version 1.2.1) Perhaps I should try the new one.

**Comment by dainnilsson** [comment]
Yeah, that would be worth a shot. You can opt-in to the beta channel from the Play store.
One other thing you might want to try is to clear out the apps data completely (Storage > Clear data) and completely uninstall the app, and then reinstall. It might be that something in the transfer from the old phone messed things up.

**Comment by SturmB** [comment]
I was accepted into the beta and downloaded it, but I'm afraid that issue still stands. I wonder if it had to do with another app I used on the Nexus 6 called "Better Open With". Sadly, it doesn't seem to work on the Note 8; at least, not for NFC taps.

**Comment by skorokithakis** [comment]
I have the same problem with a Nexus 6P, with stock Android. The app is set to open links to my.yubico.com, but the browser launches instead. I am trying a reinstallation right now and will comment here. I don't see a beta option anywhere on Google Play.

EDIT: Reinstallation worked, huh. Still, if someone can point me to the beta opt-in page, I'd appreciate it.

**Comment by SturmB** [comment]
@skorokithakis Reinstallation appears to be the magic sauce needed. I did so and it now appears to work as expected. I also left the beta channel before reinstalling it.

If you want to try the beta of it, you need to visit the app's store page using the Play Store app on your phone. _It does **not** show up on the desktop version of the the Google Play Store._ Scroll all the way to the bottom (well, _almost_ to the bottom) of the app's store page on your device and you'll see a button where you can opt in to the beta channel. It's unmistakable, so if you don't see it, something else may be wrong. Again, _this doesn't work in a desktop browser_; only in the Google Play Store app on a mobile device.

Hope that helps! 😉

**Comment by skorokithakis** [comment]
Thank you, @SturmB, I was scrolling all the way down on the desktop and only looking at the top part of the Play store on the mobile app, so I was missing it. I'm in now!

**Comment by michou** [comment]
@dainnilsson could this be reopened? Using a freshly installed (as of June 4th, 2017) YubiAuthenticator, the default behavior was to open the system browser. I had to reinstall the application (as @skorokithakis helpfully suggested) to get it to work properly.

**Comment by dainnilsson** [comment]
I don't really see the point in re-opening this issue as all this is handled by the Android system itself, so there's nothing the app can do about it unfortunately.

**Comment by michou** [comment]
Are you sure there's nothing the app can do to better / properly intercept URLs? I mean, there's a ton of other apps that properly open when accessing an app-handled URL.

**Comment by dainnilsson** [comment]
Not certain at all, but so far I haven't seen any indication that the app is doing anything wrong in this respect. One notable difference between this app and most others that handle specific URLs is that most of them aren't typically doing so over NFC, which I suspect may be playing a part in this.

**Comment by michou** [comment]
I'm going to make a test using an NFC tag and get back to you.
