### ISSUE TITLE
Android vs. Desktop behavior inconsistency

### ISSUE THREAD

**Issue by tycho** [Yubico/yubioath-android#46]
Some of my credentials have titles with multiple colons, for example:

Service:Region:AccountName

The Windows app will represent the above title something like this:

```
Service
SOMEOTP
Region:AccountName
```

The Android version truncates the title from the 2nd colon onward:

```
Service
SOMEOTP
Region
```

It looks to me like this is the problem:

https://github.com/Yubico/yubioath-android/blob/master/app/src/main/java/com/yubico/yubioath/fragments/ListCodesFragment.java#L328

Instead of `label.split(":");`, it should be `label.split(":", 1);` to only treat the first colon in the string as a delimeter.

**Comment by dainnilsson** [comment]
Yes, you're absolutely right. This will be fixed in the next version.

**Comment by dainnilsson** [comment]
Fixed.
