### ISSUE TITLE
Crash if ZXing Barcode app not installed

### ISSUE THREAD

**Issue by darkain** [Yubico/yubioath-android#47]
If the ZXing Barcode Reader App isn't installed, the Yubico Authenticator App crashes when selected "Scan Account QR-Code" from menu.

I have not had the ZXing Barcode reader app installed in the past 6 months or so because I switched to a more powerful barcode reader on my phone. 

Instead of outright crashing, there should at least be a notice mentioning the dependency. I only happened to figure out the solution on accident. 

Yubico Authenticator for Android: version 1.1.0
Phone: Samsung Galaxy S5 - SM-G900T
Android: 6.0.1, security patch level July 1st, 2016

**Comment by dainnilsson** [comment]
The new 1.2.0 version embeds a scanner, so this should no longer be a problem (available from Github releases, being pushed out to the beta channel in the Play store, to be promoted to the stable channel in a few days if no issues are reported).

**Comment by darkain** [comment]
Confirmed, working great now. Thanks!
