### ISSUE TITLE
Feature Request: Larger/configurable font for OTP codes

### ISSUE THREAD

**Issue by bperrybap** [Yubico/yubioath-android#48]
The font used for the OTP values is quite small.
It would be nice to make it quite a bit larger, perhaps even user selectable from 3 different sizes.
And for increased readability a gap between the the 3rd and 4th digit
would be nice so the user can read it as 2 sets of 3 numbers.
But if an actual space character is inserted in the display for
simplicity, then when copying it to the clipboard it should still only
copy the 6 digits.

**Comment by dainnilsson** [comment]
The new 2.0.0 UI has taken these considerations into account, You can get it from the releases page here on Github, or by signing up for beta releases on the Google Play Store page for the app.

**Comment by bperrybap** [comment]
The gap is really nice, but I don't see a way to adjust the font size. Did I miss something?
