### ISSUE TITLE
Feature Request: Dark(black)/Light theme option

### ISSUE THREAD

**Issue by bperrybap** [Yubico/yubioath-android#49]
The current background is a dark grey,
but black is best as it uses less power on certain types of displays.
Perhaps even have a user option similar to what K-9 email does which has
a "Light" and a "Dark" theme which allows users to choose what they like.
In K-9 "Dark" uses a totally black background and whereas the "Light" uses white background.

**Comment by rmenessec** [comment]
Would appreciate a proper Material Dark theme and a Material AMOLED theme. Not asking much; this is a small project with very few resources that need adapting for darker themes.

**Comment by dainnilsson** [comment]
Sounds like a nice feature indeed. I'd gladly accept a pull request for this!

**Comment by rmenessec** [comment]
@dainnilsson Sorry, not a developer. Just a customer asking for a feature. ☺

**Comment by dainnilsson** [comment]
Added by #102 for inclusion in the next release.
