### ISSUE TITLE
Blue Timer/token status bar along top is incorrect

### ISSUE THREAD

**Issue by bperrybap** [Yubico/yubioath-android#50]
It appears that the blue token timer bar along the top is counting down from time from the last scan of the Yubikey rather than timing the time until the token expires.

This is not useful and is not the way the token timers work on Google Authenticator.
In google authenticator the timers are indicating the validity of the token and are counting down to the expiration of the token.
I've never understood why google has indicators for all the tokens since they all are minute based, but in order to be useful, any countdown indicator should be showing the validity of the token(s) not just counting a minute from the time the Yubikey was scanned.

**Comment by dainnilsson** [comment]
This behavior is by design, see #44.
