### ISSUE TITLE
Doesn't work after activity has been recreated

### ISSUE THREAD

**Issue by schaal** [Yubico/yubioath-android#55]
The code list fragment doesn't get updated (no new codes appear) after the activity had to be recreated (e.g. due to OOM). The issue seems to lie in ListCodesFragment.kt:

```java
    fun showCodes(codeMap: List<Map<String, String>>) {
        if (activity == null) {
            initialCodes = codeMap
            return
        }
```
`activity` is null here after it has been recreated and the function returns without updating the list. Seems the fragment doesn't get properly reattached to its Activity in this case.

**Comment by dainnilsson** [comment]
This should be fixed in 1.2.0 (available from Github releases, being pushed out to the beta channel in the Play store, to be promoted to the stable channel in a few days if no issues are reported).
