### ISSUE TITLE
Not compatible with Android 7 on Huawei GR3 (2017)

### ISSUE THREAD

**Issue by prolic** [Yubico/yubioath-android#56]
I bought a Yubikey Neo. I am using a Huawei GR3 (2017) phone with Google Android 7 and NFC. However your Yubico Authenticator app is not compatible with my phone according to Google Play Store and I cannot even install that application.

Can I expect an update soon?

**Comment by dainnilsson** [comment]
According to Google Play, that device should be supported. If you opt in to the beta, does that make any difference? https://play.google.com/apps/testing/com.yubico.yubioath

**Comment by prolic** [comment]
Ok that worked for me, thanks.
