### ISSUE TITLE
when unplugging yubikey-4c, codes do not clear from screen

### ISSUE THREAD

**Issue by mrose17** [Yubico/yubioath-android#61]
launch yubico authenticator on android (in my case, a Pixel XL phone). the app says "Tap your YubiKey to view credentials". this is correct behavior.

connect the yubikey-4c and the codes display. this is correct behavior.

unplug the yubikey-4c and the codes continue to display, which i believe is incorrect behavior.

when the clock runs down, they do not update, which is fortunate.

i believe that the correct behavior is for the codes to clear once the yubikey-4c is removed.

**Comment by dainnilsson** [comment]
This is intended behavior, and has been kept in the new 2.0.0-alpha1 release interface. Once the YubiKey has been unplugged, you can manually clear the list of credentials by swiping the codes to the side (pre 2.0.0) or dragging them downward (2.0.0-alpha1).
