### ISSUE TITLE
Better UI

### ISSUE THREAD

**Issue by smiller171** [Yubico/yubioath-android#62]
The UI for this app is looking extremely dated, both from a beauty standpoint and a usability standpoint. (Look to Authy for better design)

I don't have much experience with Android dev, but I'd be interested in trying to put something together if you'd accept a PR.

_Sent from my Google Pixel using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by dainnilsson** [comment]
The UI is getting quite dated, and the app would benefit from an overhaul. At some point it's likely that we'll rewrite it completely, as the current UI is designed for NFC usage only, so the newly added USB support is kind of "hacked on". We'll probably accept PRs on the current UI for now if they're sensible, but submitters should be aware that sooner or later a complete redesign is inevitable.

**Comment by stp-ip** [comment]
I have > 25 codes configured and some ideas to make this easier to work with:
 * make position movable so I can set often used ones further to the top
 *  search

And as always: Thanks for the USB support. Working great so far.

**Comment by dainnilsson** [comment]
Please check out the new 2.0.0 alpha release. You can get it from the releases page here on Github, or by signing up for beta releases on the Google Play Store page for the app.

The UI has been re-designed, adding things like search and "favorite" credentials which are displayed at the top.

**Comment by smiller171** [comment]
love the new UI! especially the ability to mark favorites
