### ISSUE TITLE
Allow custom time periods

### ISSUE THREAD

**Issue by smiller171** [Yubico/yubioath-android#63]
Currently it appears that Authy does not allow for time periods other than [30 seconds](https://github.com/Yubico/yubioath-android/blob/d1b59b6818307dd7a986a0a13495ce75d4b65aec/app/src/main/kotlin/com/yubico/yubioath/fragments/ListCodesFragment.kt#L150). According to [RFC 6238](https://tools.ietf.org/html/rfc6238) while 30 seconds is recommended, it is not required. In fact Authy currently uses a 10 second period for their TOTP codes. I would like to extract a private key from authy so that I can use Yubikey instead of Authy, but can't generate codes accurately without this shorter time period being supported.

An example of how to extract codes from authy, and a QR code for testing can be found here https://gist.github.com/Ingramz/14a9c39f8c306a2d43b4

**Comment by dainnilsson** [comment]
The new 2.0.0-alpha1 release supports different time periods, please try it out. You can get it from the releases page here on Github, or by signing up for beta releases on the Google Play Store page for the app.

**Comment by smiller171** [comment]
Awesome. I just joined the beta and will try it out as soon as the update pushes to my device.
