### ISSUE TITLE
Yubikey Authenticator: Installation Issue: Samsung Galaxy S3 Phone

### ISSUE THREAD

**Issue by Jimbo550** [Yubico/yubioath-android#65]
Hello there,

I've already raised Ticket 00021462 with Yubico Support for this issue, and they suggested I raise it here if their suggested remedial steps failed (they did).

I am having problems trying to install Yubikey Authenticator Version 1.2.1 on my Samsung Galaxy S3 phone. Whenever I attempt the install, I receive an error message stating installation was not possible due to "Error Code 103". That's all I have.

I am running Android Version 4.1.2 on my phone - the I9300 variant of the Galaxy S3. The last successfully installed version of Yubikey Authenticator I was using was 1.1.0.

I did try uninstalling version 1.1.0 before installing version 1.2.1, but this failed with the same error message (Error Code 103). For the time being, I have re-installed version 1.1.0 with no issues.

Thanks in anticipation for any help.

James

**Comment by dainnilsson** [comment]
I'm thinking it might be related to the signing of the apk: https://stackoverflow.com/questions/33149140/play-store-cant-install-app-error-code-103

What about if you (after uninstalling any prior version) try downloading and installing the 1.2.1 version from here instead? https://fdroid.gitlab.io/fdroid-website/ast/packages/com.yubico.yubioath/index.html
