### ISSUE TITLE
Main intent is unresponsive after initial NFC scan then leaving intent, then returning again later

### ISSUE THREAD

**Issue by Orbixx** [Yubico/yubioath-android#66]
### Device specs:

Android version: 8.0.0 (also affected the previous major version)
Device: Huawei/Google Nexus 6P

### How to reproduce:

1. From a non-running state, run Yubioath
2. Scan Yubikey via NFC (Successful)
3. Turn screen off / go to different apps
4. Return to Yubioath
5. Attempt to scan again (No response, though the NFC scan sound does play)
6. Let out a big sigh

### Workaround:

Simply opening the 'About' intent, then returning to the main intent seems to fix this.

### Thoughts:

Based on the workaround, it seems like either finding the cause of the blocked UI or deliberately refreshing the intent when it comes back into focus should fix the issue.

**Comment by dainnilsson** [comment]
Please try the new 2.0.0-alpha1 (available on Google Play if you sign up for beta releases, or as a download on the releases page here on Github), which shouldn't have this problem. If you do encounter it, please re-open or create a new issue.

**Comment by Orbixx** [comment]
Hi Dain,

Thanks for suggesting this, this version seems to not have this problem! The UI is much improved too.
