### ISSUE TITLE
Neo does not work with Samsung Galaxy S6

### ISSUE THREAD

**Issue by kenydub** [Yubico/yubioath-android#67]
I just purchased a yubikey neo and have been trying to get it to work with a Samsung Galaxy S6 without success. The key works with Trigger - Task Launcher (https://play.google.com/store/apps/details?id=com.jwsoft.nfcactionlauncher&hl=en) on the Samsung. Gmail also works successfully with the yubikey neo. But with the authenticator I get "error in yubikey communication". I have tried the most recent version of the authenticator and earlier version at the site above again without success. Android version is 7.0 and build number is NRD90M.G920VVRS4DQH1. Any suggestions of what I can do to get this to work? Thanks.

**Comment by dainnilsson** [comment]
The reason it might be working with other apps like Trigger is that the NFC communication used there is much simpler, with fewer round-trips and less data being transmitted. The functionality used by Yubico Authenticator is a bit more advanced and requires a more reliable NFC connection to work. Antenna size/quality vary a lot between different phone models. What I usually find is that once you find the "sweet spot" you can usually get it working quite reliably, but you almost have to google to find out where your particular phone has its antenna placed to find out where to hold the YubiKey. Once you know the spot, you typically need to place the YubiKey flat against the back of your phone for a second or so, until you get feedback from the app that it has completed the current action (listing codes, etc).

You could try using the desktop version of Yubico Authenticator over USB to make sure the functionality works as expected, just to rule out any malfunction in the YubiKey itself.

**Comment by dainnilsson** [comment]
Closing this since it doesn't look like it's an actual issue with the app.
