### ISSUE TITLE
Additional confirmation of delete / undelete?

### ISSUE THREAD

**Issue by STRML** [Yubico/yubioath-android#7]
Just yesterday I was syncing two yubikeys. I had an extra account on one with a similar name to the others and deleted it, or so I thought - I ended up deleting my only copy of an important account key. Now I'm locked out and dealing with their support line.

Authy has some really good ideas here in terms of user-friendliness. Would it be possible to implement a delete mechanism where the code is simply disabled and recoverable for 48 hours - and if the key is scanned again after that 48 hours is up, the code is permanently deleted. I think a lot of people realize too late when they delete an account and this would be a big help.

Thoughts?

**Comment by dainnilsson** [comment]
I think for this feature to be useful the ykneo-oath project needs modification, adding a lot of new complexity to it. If the applet does add functionality then this app will surely take advantage of that, but until then I'm closing this issue.
