### ISSUE TITLE
Crash when loading SVG as a custom icon

### ISSUE THREAD

**Issue by edent** [Yubico/yubioath-android#72]
I tried loading an SVG as an icon. This caused the app to crash and quit.

```
10-21 16:41:15.876 12636 12636 E AndroidRuntime: FATAL EXCEPTION: main
10-21 16:41:15.876 12636 12636 E AndroidRuntime: Process: com.yubico.yubioath, PID: 12636
10-21 16:41:15.876 12636 12636 E AndroidRuntime: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=65538, result=-1, data=Intent { dat=content://com.android.providers.downloads.documents/document/6181 flg=0x1 }} to activity {com.yubico.yubioath/com.yubico.yubioath.ui.main.MainActivity}: java.lang.IllegalStateException: MediaStore.Images.Media.…ntentResolver, data.data) must not be null
10-21 16:41:15.876 12636 12636 E AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4126)
10-21 16:41:15.876 12636 12636 E AndroidRuntime: 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4169)
10-21 16:41:15.876 12636 12636 E AndroidRuntime: 	at android.app.ActivityThread.-wrap20(ActivityThread.java)
10-21 16:41:15.876 12636 12636 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1552)
10-21 16:41:15.876 12636 12636 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
10-21 16:41:15.876 12636 12636 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
10-21 16:41:15.876 12636 12636 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6186)
10-21 16:41:15.876 12636 12636 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
10-21 16:41:15.876 12636 12636 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
10-21 16:41:15.876 12636 12636 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
10-21 16:41:15.876 12636 12636 E AndroidRuntime: Caused by: java.lang.IllegalStateException: MediaStore.Images.Media.…ntentResolver, data.data) must not be null
10-21 16:41:15.876 12636 12636 E AndroidRuntime: 	at com.yubico.yubioath.ui.main.CredentialsFragment.a(Unknown Source)
10-21 16:41:15.876 12636 12636 E AndroidRuntime: 	at android.support.v4.a.j.onActivityResult(Unknown Source)
10-21 16:41:15.876 12636 12636 E AndroidRuntime: 	at com.yubico.yubioath.ui.main.MainActivity.onActivityResult(Unknown Source)
10-21 16:41:15.876 12636 12636 E AndroidRuntime: 	at android.app.Activity.dispatchActivityResult(Activity.java:6937)
10-21 16:41:15.876 12636 12636 E AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4122)
10-21 16:41:15.876 12636 12636 E AndroidRuntime: 	... 9 more
10-21 16:41:15.879   886  4311 W ActivityManager:   Force finishing activity com.yubico.yubioath/.ui.main.MainActivity
```
I used an SVG from my collection of tiny icons - https://github.com/edent/SuperTinySocialIcons

May I suggest pre-loading the app with SVGs of popular services? Most people don't keep icons on their phones.  The SVGs really are tiny, under 1KB each. [Facebook is a mere 244 bytes](https://edent.github.io/SuperTinySocialIcons/tiny/facebook.svg).

**Comment by dainnilsson** [comment]
I took a quick look at adding support for SVG, but it seems trickier than one would think. It doesn't seem to be supported natively, and the library most seem to reference is unmaintained and has been [broken since Marshmallow](https://stackoverflow.com/questions/33035866/android-6-0-marshmallow-static-initialization-exception-on-getdeclaredfield). I'm continuing to investigate the issue.

Regarding bundled icons I'm a bit concerned about copyright/trademark violation. It's really an area that's outside of my comfort zone.

**Comment by edent** [comment]
I can't help with the SVG issue, but regarding logos all of the ones I have on https://github.com/edent/SuperTinySocialIcons are suitable for use in Open Source projects.

I've made sure that they are all tagged with the correct licences. Mostly CC, MIT, Apache etc.

From a  usability point-of-view having built in icons makes it much easier to see which account is which.

I'm happy to convert them to PNG if that's better for Android.

**Comment by edent** [comment]
Ah, it looks like I can easily convert them to [Android Vector Drawables](https://developer.android.com/guide/topics/graphics/vector-drawable-resources.html) if that would help?

**Comment by dainnilsson** [comment]
I actually found this fork of the library I was looking at, which might work out for loading SVGs: https://github.com/Pixplicity/sharp
I haven't had a chance to try it out yet though.

**Comment by dainnilsson** [comment]
Closing this now as the current version supports SVGs.
