### ISSUE TITLE
2.0.0-alpha2 unstable

### ISSUE THREAD

**Issue by gene1wood** [Yubico/yubioath-android#73]
I installed the beta tester 2.0.0-alpha2 but it's just very unstable.

* Every time I touch my yubikey to my phone it launches the app but there are no codes. I then have to take my yubikey away, wait, then bring it back to generate codes.
* 80% of the time after fetching codes when I come back to my phone the app has crashed and I send a report through the android or play store crash report system. I'm not sure where these reports go but there should be a number of them in there for this version.

I've reverted back to stable for now.

If this isn't obviously reproducible for others and there are steps I can perform to gather information on these two problems let me know.

**Comment by dainnilsson** [comment]
Thanks for the report, I'm going to look through the submitted crashes now. Hopefully they'll provide more information as to what's going on!

**Comment by dainnilsson** [comment]
I wasn't able to provoke the same crash on my end, but based on the crash report I believe I've found the cause and fixed it. I've just published alpha3 which will become available in the Play store beta channel shortly. Hopefully it should work better, please let me know!

**Comment by gene1wood** [comment]
Whoa, 🎉  🎊  🎈 !!!!!
Ya, that totally fixed both problems. @dainnilsson thank you! I was not expecting much out of my unspecific bug report with little diagnostic info.

**Comment by dainnilsson** [comment]
Excellent, thanks for letting us know (and for reporting the issue)!
