### ISSUE TITLE
"_hidden" entries visible in 2.x alpha builds

### ISSUE THREAD

**Issue by ajorg** [Yubico/yubioath-android#74]
Since updating to the earliest 2.0.0, I've been seeing two entries that I didn't add, both titled `_hidden`, both identified with `WHello:[...]`. One has `=AuthKey` and the other has `=DeviceKey`. It's not clear if it's safe to delete these, or if they should be hidden by the app (probably?).

**Comment by dainnilsson** [comment]
Thanks for reporting, this is indeed a bug and those should be hidden. These are credentials used for Windows Hello.

**Comment by ajorg** [comment]
Ah! Cool. Thanks for clearing that up.
