### ISSUE TITLE
Unfortunately has stopped errors when scanning key after v2 update

### ISSUE THREAD

**Issue by Gwildor** [Yubico/yubioath-android#75]
Hello!

A few days ago I installed the v2 update, and ever since then I keep getting "Unfortunately, Yubico Authenticator has stopped" errors when I scan my YubiKey NEO using NFC on my Nexus 5 running Android 5.1.1 (build number LMY48B). Clearing cache, force stopping and rebooting did not work.

I solved this by uninstalling the app using adb (`adb -d shell`, `pm uninstall -k com.yubico.yubioath`) and then installing the apk of 1.2.1. Fortunately, this allowed me to successfully scan my YubiKey again, and so I have access to my codes again.

I'm not sure what caused this, but needless to say I will stick to 1.2.1 for now. My phone is a bit broken since I rooted it after I got it, and then unrooted it again in an attempt to upgrade to Android 6 (unrooting worked, flashing images failed), so it might be something related to just my phone, but wanted to you let you know regardless. I submitted a report when Android gave me that option, hope that helps.

**Comment by dainnilsson** [comment]
Closing this as I think it might have been related to an issue that was fixed in 2.0.1. If the problem persists, please feel free to reopen this issue.
