### ISSUE TITLE
Press button for code not working on Android Authenticator 

### ISSUE THREAD

**Issue by a-self-propelled-grape** [Yubico/yubioath-android#78]
Press button for code not working on Android Authenticator for me on a Samsung S5 running Android 7.1.2 LineageOS version 14.1-20180222-NIGHTLY-llte. 

I have also tried it on a Samsung J5 (SM-J500FN) running Android 6.0.1 Build MMB29M.J500FNXXU1BQF2 and it does the same on that.

**Comment by dainnilsson** [comment]
Can you elaborate a bit on how it isn't working? Steps to reproduce, etc.
Also, what version number is displayed as "OATH Version" in the app if you open the About dialog in Settings when your YubiKey is connected?

**Comment by kinghrothgar** [comment]
I'm not sure if I should piggy back on this or create a new issue, but I'm having the same problem.

Versions and Info:
Phone: 
- Model: Pixel
- Android Version: 9.0
- Yubico Authenticator: 2.0.1

YubiKey 4:
OATH Version: 4.3.7
Firmware: 4.3.7
CCID Enabled

When I plug the YubiKey in with an adapter I a message pops up saying "No credentials stored" and pressing the button does nothing and the light on the YubiKey button stays lit.

**Comment by devJ0n** [comment]
I also get an messsage saying "No credentials stored" on my Android.

Android version 9

**Comment by kevinoid** [comment]
I'm using a YubiKey 5 NFC with Yubico Authenticator for Android 2.1.0 (OATH Version 5.1.2).  For me, "Press button for code" works when the YubiKey is connected via USB.  When the YubiKey is connected via NFC, tapping accounts with "Press button for code" on screen has no effect (it does not show the "Tap or insert your YubiKey" message nor does the button light up on the YubiKey).  Pressing the button on the YubiKey after tapping the account on-screen also has no effect.

Can you confirm whether OATH accounts with "Require touch on YubiKey to generate code" enabled should work via NFC?  If not, could an error message be added?  If so, what can we do to debug further?

Thanks!

**Comment by dainnilsson** [comment]
Regarding the "No credentials stored" message, this simply indicates that yous YubiKey doesn't have any OATH credentials stored. You need to add credentials to it before it will contain anything.

@kevinoid Require touch should work with NFC, tapping the "refresh" button next to the credential should prompt you to again tap your YubiKey to generate the code. Please try the latest beta version of the app and see if this problem persists (and re-open if that's the case!). 2.2.0-rc4 was just released, and will be rolling out to users who have oped in to the beta channel.
