### ISSUE TITLE
Communication error Samsung Galaxy S8

### ISSUE THREAD

**Issue by dariush624** [Yubico/yubioath-android#84]
Many times when I use my yubikey neo with the authenticator I hear a sound, but a popup is showed saying "Yubikey Authentication error".

Sometimes I have to try two or three times in order to get the app show my codes.

**Comment by dainnilsson** [comment]
The sound indicates that the connection is made, but the error indicates that the connection is broken before the code calculation is completed. Getting a good connection over NFC can be troublesome on some phones, and finding the exact "sweet spot" where the NFC antenna is usually helps a lot. Having a case on the phone can also make it difficult to get a good connection.

One more thing you can try is to enable or disable "NFC reader mode" from the app settings. This setting may improve the connection on some phones.
