### ISSUE TITLE
yubikey 5c (usb-c) popup "Open Yubico Authenticator when connecting this USB-device?"

### ISSUE THREAD

**Issue by jtheuer** [Yubico/yubioath-android#85]
Everytime I plug in my yubikey 5c on my android (huawaii p20)I get a message saying "Open Yubico Authenticator when connecting this USB-device?"

I can only say "always open with yubico authenticator" but I can't say "never". 

The problem is: If I say always, then I cannot use the stick as u2f device when I login on chrome, because it opens the "yubico authenticator" app instead of logging me in.
It seems that the "Google Play Services" must be the default action but yubico authenticator tries to overwrite this each time I plug in my stick.

Any idea how I can get this solved?

**Comment by dainnilsson** [comment]
Unfortunately this is all handled by Android own USB device handling which is outside the app (and leaves quite a bit to be desired). I don't have a solution for this, but some pointers for you (or anyone else who stumbles upon this):

If you've set it to always open and no longer want it, you can "unset" it by going into the _App info_ (long press the app icon, then tap _App Info_), then under _Advanced_ > _Open by default_ you can _Clear defaults_. It will then again prompt you each time.

Even if you have it set to always launch Yubico Authenticator, you can still use it in Chrome by inserting the YubiKey _before_ trying to use it. Yubico Authenticator will launch, but you can then switch apps back to Chrome and perform the log in, without removing the YubiKey.

Sorry, I wish I had some better solution.
