### ISSUE TITLE
Can't unlock Yubikey when password-protected with leading spaces

### ISSUE THREAD

**Issue by mattfloat** [Yubico/yubioath-android#90]
A password-protected Yubikey cannot be unlocked with yubioath-android *if* the password contains leading spaces. This is because the user's input into the password field gets trimmed:

https://github.com/Yubico/yubioath-android/blob/5d3c57090f89354997b79ee64f1cecd9baef07b6/app/src/main/kotlin/com/yubico/yubioath/ui/RequirePasswordDialog.kt#L79

This wouldn't seem as critical if it wasn't possible to *set* such a password with the app in the first place. But it is: user input does not get trimmed in the "set password" dialog.
As a result, a user will have to use something other than yubioath-android to unlock and change his password, e.g. yubioath-desktop.

**Comment by dainnilsson** [comment]
Thanks for spotting this!
