### ISSUE TITLE
Feature request:iOS version

### ISSUE THREAD

**Issue by rggjan** [Yubico/yubioath-android#91]
An iOS version of this app would be awesome :)

**Comment by rggjan** [comment]
Why doesn't it work with the NFC YubiKeys?
Also, if it doesn't belong here, where can I put the feature request?

**Comment by dainnilsson** [comment]
The NFC APIs on iOS only allow reading from NDEF tags, with no way to do the bidirectional communication that this application requires.

As for the feature request, you can consider it requested. 🙂
