### ISSUE TITLE
Feature request:  enumeration of stored credentials/storage slots available

### ISSUE THREAD

**Issue by AboveMyPaygrade** [Yubico/yubioath-android#92]
Hi there!  I currently have a Yubikey 4 Neo, and use it primarily for the OTP and TOTP abilities.  More and more sites are offering 2FA (if only more used U2F), and from Yubico's website, I know that my version of the Yubikey has 28 slots available for TOTP secrets (though some Yubikeys offer 24).

I have a good number of those slots filled, but I'm never really sure how many secrets I have stored or how many slots are available without manually counting them (I add and remove secrets on a semi-regular basis).  Is it possible to request a counter on the credential and an overall credential counter on the top that would provide this information at a glance?  It would provide (in my opinion) useful information on the state of the Yubikey, and would make comparing two separate Yubikeys' credential storage much easier (for example, in the case of a spare Yubikey).

The only real issue with this, which I'm not entirely sure how to remedy, is that it's still laborious to check whether a a spare Yubikey has the same credentials stored on it as the one being compared.  For example, my proposed feature would at allow one to tell at a glance whether two keys have the same number of credentials stored, but it would not tell you if the credentials in Yubikey A are the same as those stored in Yubikey B, without manually scrolling through each one.

I've included a mock-up of my proposed feature; please forgive its crude nature.  Thank you for all your work on this amazing product.

![auth - copy](https://user-images.githubusercontent.com/8353548/51396149-81a2d300-1b0c-11e9-91da-db4ca07cd32d.PNG)

**Comment by dan2468** [comment]
A good idea.

I’d suggest only starting showing a message (e.g. “5 slots remaining”) when adding.

The user could take that warning as a sign to clean-up, which should be clearly documented, as being locked out of even nonessential accounts can be pretty stressful (as I can tell you).

I see no point in worrying people in the beginning, with a prominent counter, nor does the slot number seem to me that useful/actionable.

**Comment by AboveMyPaygrade** [comment]
The message alone could work; the persistent notification is more of a preference of mine (though I only somewhat recently realized that different models of Yubikey have different amounts of storage available for credentials, which is why I find that specific suggestion helpful).  As for the numbering to the side of each credential, I like this if only because it makes side-by-side comparison of multiple Yubikeys much easier for me:  if spare Yubikey 1 has a Github credential in slot 19, but spare Yubikey 2 has a Dropbox credential in slot 19, I know there's an issue I need to remedy.  It's not a perfect solution, but it's useful.

**Comment by AdamVe** [comment]
Sorry for the late response. The development of the app moved to https://github.com/Yubico/yubioath-flutter. The new version shows the account counter for YubiKeys with firmware > 4.0.0. Please reopen this issue in the new repository if still needed.
