### ISSUE TITLE
F-Droid package is a year old, please update

### ISSUE THREAD

**Issue by ShapeShifter499** [Yubico/yubioath-android#93]
I'm noticing the F-Droid package is a year old. The page for the application is mentioning the source is no longer available. Seems the source is here so why is the F-Droid package so out of date?
![screenshot_20190126-060728](https://user-images.githubusercontent.com/388665/51788295-2cc91300-2131-11e9-85d2-974772cd8c97.png)

**Comment by dainnilsson** [comment]
Hi. I'm not sure why FDroid isn't up to date. We don't maintain anything at FDroid, so you'll have to contact them to find out more.

**Comment by ShapeShifter499** [comment]
For anyone following this, I posted the issue here https://gitlab.com/fdroid/fdroiddata/issues/1523

**Comment by licaon-kter** [comment]
Is `play-services-vision` open source? I'll guess not...

@dainnilsson Any chance of a non-gms flavour than doesn't need that?

**Comment by licaon-kter** [comment]
@ShapeShifter499 You've seen? Links please...

**Comment by ShapeShifter499** [comment]
@licaon-kter I might have misunderstood but there is this tag "NonFreeAssets" in F-Droid. I haven't kept much attention on this though.  Searching F-Droid brings up this https://search.f-droid.org/?q=NonFreeAssets&lang=en  But maybe F-Droid is cracking down on this more?

**Comment by licaon-kter** [comment]
@ShapeShifter499 Read: https://f-droid.org/wiki/page/Antifeature:NonFreeAssets

Now read my post again, libs needed for app building is something else.

**Comment by dainnilsson** [comment]
The app uses Google Mobile Services (GMS) for QR scanning when available, but will additionally attempt to use an external QR scanner if GMS are not available (meaning it will run on devices without GMS). To do this it does need to include some Google code. I don't think we'd be interested in maintaining two different variants of this codebase, but I'd be open to accepting changes that unobtrusively allow building a non-GMS version from the same project. I'm not sure how that would best be implemented practically though, and it isn't a priority for us right now.

**Comment by IzzySoft** [comment]
@dainnilsson please take a look at [build variants](https://developer.android.com/studio/build/build-variants). Many projects use "build flavors" to provide a FOSS variant next to their Playstore builds.

Before you ask: I'm not a dev, I cannot provide a PR for this, sorry.

**Comment by licaon-kter** [comment]
> please take a look at build variants

FYI, if you follow that, please don't use a suffix, as it currently breaks autoupdates. :)

**Comment by IzzySoft** [comment]
@licaon-kter is that why the AndroidAuthority guide skips them? 😃
