### ISSUE TITLE
"No QR code reader available"

### ISSUE THREAD

**Issue by koorg** [Yubico/yubioath-android#94]
Symptoms :
- APK installation : OK
- start the app
- attach yubikey : detected
- click "+"
- select "scan QR code"
- "No QR code reader available"

Context :
- no google apps or libs installed
- a QR code scanning app exists
- yubico authenticator has camera access (verified)

Suggestion :
- embed a QR code feature within the authenticator : will remove the risk of potentially backdoored QR app usage
- offer the ability to manually select a QR scanning app

**Comment by koorg** [comment]
I can confirm it works with com.google.zxing.client.android
The app used was custom

**Comment by tadzik** [comment]
Anything recommended (maybe from f-droid) for those of us not using Google Play?

**Comment by armanborghem** [comment]
I get the same message, "No QR code reader available" even though I have installed this FOSS QR code app which belongs to a German university. https://f-droid.org/en/packages/com.secuso.privacyFriendlyCodeScanner/

**Comment by zeugor** [comment]
I don't have neither Google Play Services, and as @armanborghem I have also QR Scanner, https://f-droid.org/en/packages/com.secuso.privacyFriendlyCodeScanner/, and getting same error, as well: "No QR code reader available". 

Why can't YubiKey-Auth locate this external QR app? Is it a YubiKey-Auth app issue? or Is QR-Scanner issue?

**Comment by RononDex** [comment]
Any update on this?

**Comment by cavatron** [comment]
To extend the solution @koorg found... 

For anyone using Calyx, Graphene, etc. who does not have Google Play Services, you can use any ZXing-based QR scanner, and Yubico Authenticator QR scan will work.  

Relevant code lines [here](https://github.com/Yubico/yubioath-android/blob/8fbb3b1fadaae2a40429e2cd78be80bd5adcb1a8/app/src/main/kotlin/com/yubico/yubioath/ui/main/CredentialFragment.kt#L177) and [here](https://github.com/Yubico/yubioath-android/blob/8fbb3b1fadaae2a40429e2cd78be80bd5adcb1a8/app/src/main/kotlin/com/yubico/yubioath/ui/main/CredentialFragment.kt#L269)

If you have microG, get the official [ZXing client](https://github.com/zxing/zxing) from Aurora Store

Without microG or if you just prefer to get apps through F-Droid, use [Binary Eye](https://github.com/markusfisch/BinaryEye), a ZXing-based QR code scanner.

I just installed Binary Eye on my Pixel 4 XL with Calyx and now Yubico Authenticator will open Binary Eye to scan codes
