### ISSUE TITLE
Worked on Samsung S4 mini, doesn't work on Samsung S9

### ISSUE THREAD

**Issue by madhatter0** [Yubico/yubioath-android#95]
Both phones are running LineageOS 15.1 (Android 8.1.0).  The S4 Mini is running the f-droid yubioath code, so v2.0.1, and has been working with my Neo for some time.  The S9, on either 2.0.1 (from f-droid) or 2.1.0 (from here), makes a sound when the Neo is presented, but no password prompt appears, nor any TOTP codes.

With 2.1.0, I've tried both with and without "NFC reader mode".  In all cases I get either the negative-result sound, or the positive-result sound and a haptic wiggle, but nothing more.

**Comment by dan2468** [comment]
Offtopic, but are you sure your Samsung Galaxy S4 Mini (International LTE a.k.a. serranoltexx, or International 3G a.k.a. serrano3gxx, or International Dual SIM a.k.a. serranodsdd) has LineageOS version 15.1?
I have the last version 14.1 nightly OS build (2018-06-24, Android 7.1.2) and there are no updates since development has been discontinued.

**Comment by madhatter0** [comment]
Good question, but yes, I am; I've been using arco68's unofficial builds on my serranoltexx since the S4 mini went out of mainstream support.  If you're interested, you can find them [here](https://www.mediafire.com/folder/rpgoccwooz2du/serranoltexx); (s)he's doing them for 16.0 as well as 15.1, and even 14.1 in case you just want to keep up with Android security patch releases.

However, I've been using my yubikey via NFC to do TOTP OATH for at least a couple of years, back to mainstream 14.1 if not before, so I don't think the serranoltexx builds are the issue.

**Comment by mrmekon** [comment]
@madhatter0 This seems to be a problem with certain builds of LineageOS.  I have a phone (Samsung S8, LineageOS 15.1) that exhibits the same behavior, and it looks like it might be caused by the LineageOS kernel handling Mifare tags incorrectly.

Yubikey NEOs, which use Mifare, are read incorrectly by all NFC readers on the affected phone.  You can verify with Yubico Authenticator, OpenKeychain, and NXP TagInfo.  Yubikey 5 devices, on the other hand, do not use Mifare and are read correctly.

If you want to report this to the LineageOS developers, some lines of interest from the Android logs when failing to parse a Mifare key are:

```
03-04 14:30:50.595 13540 13540 E NxpExtns: Mifare : phLibNfc_GetKeyNumberMFC Key found
03-04 14:30:50.595 13540 13540 E NxpExtns: Mifare : phLibNfc_GetKeyNumberMFC returning = 0x0 Key = 0x0
...
03-04 14:30:50.626  3323 21472 I SecHAL  : nfc_data_callback: !
03-04 14:30:50.626 13540 21470 I BrcmNfcNfa: NFC received ntf gid:1
03-04 14:30:50.627 13540 21470 I BrcmNfcNfa: p2p priority is running under bail out mode ONLY.
03-04 14:30:50.627 13540 21470 I BrcmNfcNfa: nfc_set_state 4 (IDLE)->5 (OPEN)
03-04 14:30:50.627 13540 21470 I BrcmNfcNfa: nfc_ncif_proc_activate:23 0, mode:0x00
03-04 14:30:50.627 13540 21470 I BrcmNfcNfa: nfa_dm_disc_discovery_cback (): event:0x4004
03-04 14:30:50.627 13540 21470 I BrcmNfcNfa: nfa_dm_disc_sm_execute (): state: W4_HOST_SELECT (3), event: ACTIVATED_NTF(5) disc_flags: 0x1
03-04 14:30:50.627 13540 21470 I BrcmNfcNfa: nfa_dm_disc_new_state (): old_state: W4_HOST_SELECT (3), new_state: POLL_ACTIVE (4) disc_flags: 0x1
03-04 14:30:50.627 13540 21470 I BrcmNfcNfa: nfa_dm_disc_notify_activation (): tech_n_mode:0x0, proto:0x81
03-04 14:30:50.627 13540 21470 I BrcmNfcNfa: nfa_dm_disc_get_disc_mask (): tech_n_mode:0x0, protocol:0x81, disc_mask:0x2000
03-04 14:30:50.627 13540 21470 I BrcmNfcNfa: activated_protocol:0x81, activated_handle: 0x1
03-04 14:30:50.627 13540 21470 I BrcmNfcNfa: nfa_dm_poll_disc_cback (): event:0x01
03-04 14:30:50.627 13540 21470 I BrcmNfcNfa: nfa_rw_handle_event event: NFA_RW_ACTIVATE_NTF_EVT (0x501), flags: 00000001
03-04 14:30:50.627 13540 21470 I BrcmNfcNfa: nfa_rw_activate_ntf
03-04 14:30:50.627 13540 21470 I BrcmNfcNfa: nfa_dm_notify_activation_status (): status:0x0
03-04 14:30:50.627 13540 21470 I BrcmNfcNfa: nfa_dm_disc_sm_execute (): new state: POLL_ACTIVE (4), disc_flags: 0x1
03-04 14:30:50.627 13540 13540 D NativeNfcTag: Check NDEF Failed - status = 3
```

Compare to a valid Yubikey 5 response:
```
03-04 15:07:57.284  3323 21472 I SecHAL  : nfc_data_callback: !
03-04 15:07:57.285 13540 21470 I BrcmNfcNfa: NFC received ntf gid:1
03-04 15:07:57.285 13540 21470 I BrcmNfcNfa: p2p priority is running under bail out mode ONLY.
03-04 15:07:57.285 13540 21470 I BrcmNfcNfa: nfc_set_state 4 (IDLE)->5 (OPEN)
03-04 15:07:57.285 13540 21470 I BrcmNfcNfa: nfc_ncif_proc_activate:41 18, mode:0x00
03-04 15:07:57.285 13540 21470 I BrcmNfcNfa: nfa_dm_disc_discovery_cback (): event:0x4004
03-04 15:07:57.285 13540 21470 I BrcmNfcNfa: nfa_dm_disc_sm_execute (): state: W4_HOST_SELECT (3), event: ACTIVATED_NTF(5) disc_flags: 0x1
03-04 15:07:57.286 13540 21470 I BrcmNfcNfa: nfa_dm_disc_new_state (): old_state: W4_HOST_SELECT (3), new_state: POLL_ACTIVE (4) disc_flags: 0x1
03-04 15:07:57.286 13540 21470 I BrcmNfcNfa: nfa_dm_disc_notify_activation (): tech_n_mode:0x0, proto:0x4
03-04 15:07:57.286 13540 21470 I BrcmNfcNfa: nfa_dm_disc_get_disc_mask (): tech_n_mode:0x0, protocol:0x4, disc_mask:0x4
03-04 15:07:57.286 13540 21470 I BrcmNfcNfa: activated_protocol:0x4, activated_handle: 0x1
03-04 15:07:57.286 13540 21470 I BrcmNfcNfa: nfa_dm_poll_disc_cback (): event:0x01
03-04 15:07:57.286 13540 21470 I BrcmNfcNfa: nfa_rw_handle_event event: NFA_RW_ACTIVATE_NTF_EVT (0x501), flags: 00000001
03-04 15:07:57.286 13540 21470 I BrcmNfcNfa: nfa_rw_activate_ntf
03-04 15:07:57.286 13540 21470 I BrcmNfcNfa: RW_SetActivatedTagType protocol:4, technology:0, SAK:32
03-04 15:07:57.286 13540 21470 I BrcmNfcNfa: rw_t4t_select ()
03-04 15:07:57.286 13540 21470 I BrcmNfcNfa: nfa_dm_notify_activation_status (): status:0x0
03-04 15:07:57.287 13540 21470 I BrcmNfcNfa: nfa_dm_disc_sm_execute (): new state: POLL_ACTIVE (4), disc_flags: 0x1
03-04 15:07:57.287 13540 13540 I BrcmNfcNfa: NFA_RwDetectNDef
```

**Comment by madhatter0** [comment]
I have [opened a ticket](https://gitlab.com/LineageOS/issues/android/issues/256) with LineageOS support.

**Comment by AdamVe** [comment]
Sorry for the late response. The development of the app moved to https://github.com/Yubico/yubioath-flutter and we have released a new version of the app. Please report any new issues in the new repository.
