### ISSUE TITLE
OATH functionality missing or disabled.

### ISSUE THREAD

**Issue by navjotsinghh** [Yubico/yubioath-android#97]
On tapping Yubicokey on Samsung S8 Plus phone, I'm getting a message OATH functionality missing or disabled.

**Comment by dainnilsson** [comment]
This would indicate a YubiKey that doesn't support OATH, such as a Security Key (blue key). If you're getting this message despite being sure that the YubiKey should support OATH, then please reopen this issue and post what kind of YubiKey you have.

**Comment by brad** [comment]
Personally, I think there is still a bug in messaging/documentation here.

**Comment by tylerburleigh** [comment]
I have a Yubikey 5 NFC. I'm getting the "OATH functionality missing or disabled" error with the Yubico app, and it seems to be triggered by the magnetic strip on a metro card that I store on the back of my phone.

**Comment by Skyler0x2** [comment]
I have the same issue unfortunately. It works with google auth app just fine though.
