### ISSUE TITLE
Application crashes when trying to add OATH credential over limit

### ISSUE THREAD

**Issue by radeksimko** [Yubico/yubioath-android#99]
App Version: `2.2.0-rc2` (installed directly from the beta channel of Google Play)
OATH Version: `0.2.1`

I recently started copying (re-adding to both) 43 credentials from my old NEO key to new 5C, only to realize that the new key (5C) has less space and I can't fit all my existing credentials (which I already have on NEO) there. 😑 

https://support.yubico.com/support/solutions/articles/15000014180-yubikey-5c

When I attempt to add 33rd credential, the application just crashes.

I have sent you the feedback, as prompted by Android, not sure if that's any helpful.

-------

btw. The desktop Yubico Authenticator correctly recognizes this limitation and communicates it to the user:

![Screen Shot 2019-04-14 at 14 17 08](https://user-images.githubusercontent.com/287584/56093395-1fb1f980-5ec0-11e9-93ae-89859a135f30.png)

and the latest version of Yubikey Manager also reports this:

```
$ ykman oath uri "otpauth://totp/SourceForge:<REDACTED>?digits=6&secret=<REDACTED>&algorithm=SHA1&issuer=SourceForge&period=30"
Usage: ykman oath uri [OPTIONS] [URI]
Try "ykman oath uri -h" for help.

Error: No space left on your YubiKey for OATH credentials.
```

**Comment by dainnilsson** [comment]
This is addressed in the latest beta version of the app, which is currently being rolled out to users who have opted-in to the beta channel in the Play store (version 2.2.0-rc4).
